// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	chatsession "go-zero-voice-agent/app/llm/cmd/api/internal/handler/chatsession"
	config "go-zero-voice-agent/app/llm/cmd/api/internal/handler/config"
	"go-zero-voice-agent/app/llm/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 查询会话详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: chatsession.GetChatSessionHandler(serverCtx),
			},
			{
				// 删除会话
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: chatsession.DeleteChatSessionHandler(serverCtx),
			},
			{
				// 分页查询会话列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: chatsession.ListChatSessionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/llm/v1/chat-session"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 删除配置
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: config.DeleteConfigHandler(serverCtx),
			},
			{
				// 更新配置
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: config.UpdateConfigHandler(serverCtx),
			},
			{
				// 获取配置详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: config.GetConfigHandler(serverCtx),
			},
			{
				// 创建配置
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: config.CreateConfigHandler(serverCtx),
			},
			{
				// 分页查询我的配置
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: config.ListMyConfigHandler(serverCtx),
			},
		},
		rest.WithPrefix("/llm/v1/config"),
	)
}
