// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChatConfig struct {
	Id                int64   `json:"id"`
	Name              string  `json:"name"`
	Description       string  `json:"description"`
	UserId            int64   `json:"userId"`
	BaseUrl           string  `json:"baseUrl"`
	ApiKey            string  `json:"apiKey"`
	Model             string  `json:"model"`
	Stream            int64   `json:"stream"`
	Temperature       float64 `json:"temperature"`
	TopP              float64 `json:"topP"`
	TopK              int64   `json:"topK"`
	EnableThinking    int64   `json:"enableThinking"`
	RepetitionPenalty float64 `json:"repetitionPenalty"`
	PresencePenalty   float64 `json:"presencePenalty"`
	MaxTokens         int64   `json:"maxTokens"`
	Seed              int64   `json:"seed"`
	EnableSearch      int64   `json:"enableSearch"`
	ContextLength     int64   `json:"contextLength"`
}

type CreateConfigReq struct {
	Name              string  `json:"name"`
	Description       string  `json:"description"`
	UserId            int64   `json:"userId"`
	BaseUrl           string  `json:"baseUrl"`
	ApiKey            string  `json:"apiKey"`
	Model             string  `json:"model"`
	Stream            int64   `json:"stream"`
	Temperature       float64 `json:"temperature"`
	TopP              float64 `json:"topP"`
	TopK              int64   `json:"topK"`
	EnableThinking    int64   `json:"enableThinking"`
	RepetitionPenalty float64 `json:"repetitionPenalty"`
	PresencePenalty   float64 `json:"presencePenalty"`
	MaxTokens         int64   `json:"maxTokens"`
	Seed              int64   `json:"seed"`
	EnableSearch      int64   `json:"enableSearch"`
	ContextLength     int64   `json:"contextLength"`
}

type CreateConfigResp struct {
	Id int64 `json:"id"`
}

type DeleteConfigReq struct {
	Id int64 `path:"id"`
}

type DeleteConfigResp struct {
}

type GetConfigReq struct {
	Id int64 `path:"id"`
}

type GetConfigResp struct {
	Config ChatConfig `json:"config"`
}

type ListMyConfigReq struct {
	PageQuery   PageQuery  `json:"pageQuery"`
	QueryFilter ChatConfig `json:"queryFilter"`
}

type ListMyConfigResp struct {
	Total   int64        `json:"total"`
	Configs []ChatConfig `json:"configs"`
}

type PageQuery struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
	OrderBy  string `json:"orderBy"`
}

type UpdateConfigReq struct {
	Id                int64   `path:"id"`
	Name              string  `json:"name"`
	Description       string  `json:"description"`
	UserId            int64   `json:"userId"`
	BaseUrl           string  `json:"baseUrl"`
	ApiKey            string  `json:"apiKey"`
	Model             string  `json:"model"`
	Stream            int64   `json:"stream"`
	Temperature       float64 `json:"temperature"`
	TopP              float64 `json:"topP"`
	TopK              int64   `json:"topK"`
	EnableThinking    int64   `json:"enableThinking"`
	RepetitionPenalty float64 `json:"repetitionPenalty"`
	PresencePenalty   float64 `json:"presencePenalty"`
	MaxTokens         int64   `json:"maxTokens"`
	Seed              int64   `json:"seed"`
	EnableSearch      int64   `json:"enableSearch"`
	ContextLength     int64   `json:"contextLength"`
}

type UpdateConfigResp struct {
}
