// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rag.proto

package server

import (
	"context"

	"go-zero-voice-agent/app/rag/cmd/rpc/internal/logic/ragservice"
	"go-zero-voice-agent/app/rag/cmd/rpc/internal/svc"
	"go-zero-voice-agent/app/rag/cmd/rpc/pb"
)

type RagServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRagServiceServer
}

func NewRagServiceServer(svcCtx *svc.ServiceContext) *RagServiceServer {
	return &RagServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RagServiceServer) Query(ctx context.Context, in *pb.QueryReq) (*pb.QueryResp, error) {
	l := ragservicelogic.NewQueryLogic(ctx, s.svcCtx)
	return l.Query(in)
}

func (s *RagServiceServer) QueryMultiple(ctx context.Context, in *pb.QueryMultipleReq) (*pb.QueryResp, error) {
	l := ragservicelogic.NewQueryMultipleLogic(ctx, s.svcCtx)
	return l.QueryMultiple(in)
}
