// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: voicechat.proto

package server

import (
	"context"

	"go-zero-voice-agent/app/voicechat/cmd/rpc/internal/logic/asrconfigservice"
	"go-zero-voice-agent/app/voicechat/cmd/rpc/internal/svc"
	"go-zero-voice-agent/app/voicechat/cmd/rpc/voicechatpb"
)

type AsrConfigServiceServer struct {
	svcCtx *svc.ServiceContext
	voicechatpb.UnimplementedAsrConfigServiceServer
}

func NewAsrConfigServiceServer(svcCtx *svc.ServiceContext) *AsrConfigServiceServer {
	return &AsrConfigServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AsrConfigServiceServer) CreateAsrConfig(ctx context.Context, in *voicechatpb.CreateAsrConfigRequest) (*voicechatpb.CreateAsrConfigResponse, error) {
	l := asrconfigservicelogic.NewCreateAsrConfigLogic(ctx, s.svcCtx)
	return l.CreateAsrConfig(in)
}

func (s *AsrConfigServiceServer) GetAsrConfig(ctx context.Context, in *voicechatpb.GetAsrConfigRequest) (*voicechatpb.GetAsrConfigResponse, error) {
	l := asrconfigservicelogic.NewGetAsrConfigLogic(ctx, s.svcCtx)
	return l.GetAsrConfig(in)
}

func (s *AsrConfigServiceServer) UpdateAsrConfig(ctx context.Context, in *voicechatpb.UpdateAsrConfigRequest) (*voicechatpb.UpdateAsrConfigResponse, error) {
	l := asrconfigservicelogic.NewUpdateAsrConfigLogic(ctx, s.svcCtx)
	return l.UpdateAsrConfig(in)
}

func (s *AsrConfigServiceServer) DeleteAsrConfig(ctx context.Context, in *voicechatpb.DeleteAsrConfigRequest) (*voicechatpb.DeleteAsrConfigResponse, error) {
	l := asrconfigservicelogic.NewDeleteAsrConfigLogic(ctx, s.svcCtx)
	return l.DeleteAsrConfig(in)
}

func (s *AsrConfigServiceServer) ListAsrConfig(ctx context.Context, in *voicechatpb.ListAsrConfigRequest) (*voicechatpb.ListAsrConfigResponse, error) {
	l := asrconfigservicelogic.NewListAsrConfigLogic(ctx, s.svcCtx)
	return l.ListAsrConfig(in)
}
