// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	user "go-zero-voice-agent/app/usercenter/cmd/api/internal/handler/user"
	"go-zero-voice-agent/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// auth by token
				Method:  http.MethodPost,
				Path:    "/user/auth",
				Handler: user.VerifyTokenHandler(serverCtx),
			},
			{
				// get rpc info
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.DetailHandler(serverCtx),
			},
			{
				// login
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// register
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				// send code
				Method:  http.MethodPost,
				Path:    "/user/sendCode",
				Handler: user.SendCodeHandler(serverCtx),
			},
			{
				// wechat mini auth
				Method:  http.MethodPost,
				Path:    "/user/wxMiniAuth",
				Handler: user.WxMiniAuthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)
}
