// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1

package handler

import (
	"net/http"

	user "go-zero-voice-agent/app/usercenter/cmd/api/internal/handler/user"
	"go-zero-voice-agent/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// login
				Method:  http.MethodPost,
				Path:    "/rpc/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// register
				Method:  http.MethodPost,
				Path:    "/rpc/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/rpc/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// get rpc info
				Method:  http.MethodGet,
				Path:    "/rpc/info",
				Handler: user.DetailHandler(serverCtx),
			},
			{
				// wechat mini auth
				Method:  http.MethodPost,
				Path:    "/rpc/wxMiniAuth",
				Handler: user.WxMiniAuthHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/rpc/v1"),
	)
}
