// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	doc "go-zero-voice-agent/app/rag/cmd/api/internal/handler/doc"
	"go-zero-voice-agent/app/rag/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 删除上传文件
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: doc.DeleteDocHandler(serverCtx),
			},
			{
				// 分页查询上传文件
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: doc.ListDocHandler(serverCtx),
			},
			{
				// 上传文件并向量化
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: doc.UploadAndEmbedHandler(serverCtx),
			},
		},
		rest.WithPrefix("/rag/v1/doc"),
	)
}
