// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package server

import (
	"context"

	"go-zero-voice-agent/app/llmservice/cmd/rpc/internal/logic"
	"go-zero-voice-agent/app/llmservice/cmd/rpc/internal/svc"
	"go-zero-voice-agent/app/llmservice/cmd/rpc/pb"
)

type LlmserviceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLlmserviceServer
}

func NewLlmserviceServer(svcCtx *svc.ServiceContext) *LlmserviceServer {
	return &LlmserviceServer{
		svcCtx: svcCtx,
	}
}

func (s *LlmserviceServer) CreateChat(ctx context.Context, in *pb.CreateChatReq) (*pb.CreateChatResp, error) {
	l := logic.NewCreateChatLogic(ctx, s.svcCtx)
	return l.CreateChat(in)
}
