// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: voicechat.proto

package asrconfigservice

import (
	"context"

	"go-zero-voice-agent/app/voicechat/cmd/rpc/voicechatpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AsrConfig               = voicechatpb.AsrConfig
	CreateAsrConfigRequest  = voicechatpb.CreateAsrConfigRequest
	CreateAsrConfigResponse = voicechatpb.CreateAsrConfigResponse
	CreateTtsConfigRequest  = voicechatpb.CreateTtsConfigRequest
	CreateTtsConfigResponse = voicechatpb.CreateTtsConfigResponse
	DeleteAsrConfigRequest  = voicechatpb.DeleteAsrConfigRequest
	DeleteAsrConfigResponse = voicechatpb.DeleteAsrConfigResponse
	DeleteTtsConfigRequest  = voicechatpb.DeleteTtsConfigRequest
	DeleteTtsConfigResponse = voicechatpb.DeleteTtsConfigResponse
	GetAsrConfigRequest     = voicechatpb.GetAsrConfigRequest
	GetAsrConfigResponse    = voicechatpb.GetAsrConfigResponse
	GetTtsConfigRequest     = voicechatpb.GetTtsConfigRequest
	GetTtsConfigResponse    = voicechatpb.GetTtsConfigResponse
	ListAsrConfigRequest    = voicechatpb.ListAsrConfigRequest
	ListAsrConfigResponse   = voicechatpb.ListAsrConfigResponse
	ListTtsConfigRequest    = voicechatpb.ListTtsConfigRequest
	ListTtsConfigResponse   = voicechatpb.ListTtsConfigResponse
	PageQuery               = voicechatpb.PageQuery
	TtsConfig               = voicechatpb.TtsConfig
	UpdateAsrConfigRequest  = voicechatpb.UpdateAsrConfigRequest
	UpdateAsrConfigResponse = voicechatpb.UpdateAsrConfigResponse
	UpdateTtsConfigRequest  = voicechatpb.UpdateTtsConfigRequest
	UpdateTtsConfigResponse = voicechatpb.UpdateTtsConfigResponse

	AsrConfigService interface {
		CreateAsrConfig(ctx context.Context, in *CreateAsrConfigRequest, opts ...grpc.CallOption) (*CreateAsrConfigResponse, error)
		GetAsrConfig(ctx context.Context, in *GetAsrConfigRequest, opts ...grpc.CallOption) (*GetAsrConfigResponse, error)
		UpdateAsrConfig(ctx context.Context, in *UpdateAsrConfigRequest, opts ...grpc.CallOption) (*UpdateAsrConfigResponse, error)
		DeleteAsrConfig(ctx context.Context, in *DeleteAsrConfigRequest, opts ...grpc.CallOption) (*DeleteAsrConfigResponse, error)
		ListAsrConfig(ctx context.Context, in *ListAsrConfigRequest, opts ...grpc.CallOption) (*ListAsrConfigResponse, error)
	}

	defaultAsrConfigService struct {
		cli zrpc.Client
	}
)

func NewAsrConfigService(cli zrpc.Client) AsrConfigService {
	return &defaultAsrConfigService{
		cli: cli,
	}
}

func (m *defaultAsrConfigService) CreateAsrConfig(ctx context.Context, in *CreateAsrConfigRequest, opts ...grpc.CallOption) (*CreateAsrConfigResponse, error) {
	client := voicechatpb.NewAsrConfigServiceClient(m.cli.Conn())
	return client.CreateAsrConfig(ctx, in, opts...)
}

func (m *defaultAsrConfigService) GetAsrConfig(ctx context.Context, in *GetAsrConfigRequest, opts ...grpc.CallOption) (*GetAsrConfigResponse, error) {
	client := voicechatpb.NewAsrConfigServiceClient(m.cli.Conn())
	return client.GetAsrConfig(ctx, in, opts...)
}

func (m *defaultAsrConfigService) UpdateAsrConfig(ctx context.Context, in *UpdateAsrConfigRequest, opts ...grpc.CallOption) (*UpdateAsrConfigResponse, error) {
	client := voicechatpb.NewAsrConfigServiceClient(m.cli.Conn())
	return client.UpdateAsrConfig(ctx, in, opts...)
}

func (m *defaultAsrConfigService) DeleteAsrConfig(ctx context.Context, in *DeleteAsrConfigRequest, opts ...grpc.CallOption) (*DeleteAsrConfigResponse, error) {
	client := voicechatpb.NewAsrConfigServiceClient(m.cli.Conn())
	return client.DeleteAsrConfig(ctx, in, opts...)
}

func (m *defaultAsrConfigService) ListAsrConfig(ctx context.Context, in *ListAsrConfigRequest, opts ...grpc.CallOption) (*ListAsrConfigResponse, error) {
	client := voicechatpb.NewAsrConfigServiceClient(m.cli.Conn())
	return client.ListAsrConfig(ctx, in, opts...)
}
