// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: llmservice.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LlmChatService_Chat_FullMethodName       = "/pb.LlmChatService/Chat"
	LlmChatService_ChatStream_FullMethodName = "/pb.LlmChatService/ChatStream"
)

// LlmChatServiceClient is the client API for LlmChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LlmChatServiceClient interface {
	Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error)
	ChatStream(ctx context.Context, in *ChatStreamReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamResp], error)
}

type llmChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLlmChatServiceClient(cc grpc.ClientConnInterface) LlmChatServiceClient {
	return &llmChatServiceClient{cc}
}

func (c *llmChatServiceClient) Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResp)
	err := c.cc.Invoke(ctx, LlmChatService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmChatServiceClient) ChatStream(ctx context.Context, in *ChatStreamReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LlmChatService_ServiceDesc.Streams[0], LlmChatService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatStreamReq, ChatStreamResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LlmChatService_ChatStreamClient = grpc.ServerStreamingClient[ChatStreamResp]

// LlmChatServiceServer is the server API for LlmChatService service.
// All implementations must embed UnimplementedLlmChatServiceServer
// for forward compatibility.
type LlmChatServiceServer interface {
	Chat(context.Context, *ChatReq) (*ChatResp, error)
	ChatStream(*ChatStreamReq, grpc.ServerStreamingServer[ChatStreamResp]) error
	mustEmbedUnimplementedLlmChatServiceServer()
}

// UnimplementedLlmChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlmChatServiceServer struct{}

func (UnimplementedLlmChatServiceServer) Chat(context.Context, *ChatReq) (*ChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedLlmChatServiceServer) ChatStream(*ChatStreamReq, grpc.ServerStreamingServer[ChatStreamResp]) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedLlmChatServiceServer) mustEmbedUnimplementedLlmChatServiceServer() {}
func (UnimplementedLlmChatServiceServer) testEmbeddedByValue()                        {}

// UnsafeLlmChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlmChatServiceServer will
// result in compilation errors.
type UnsafeLlmChatServiceServer interface {
	mustEmbedUnimplementedLlmChatServiceServer()
}

func RegisterLlmChatServiceServer(s grpc.ServiceRegistrar, srv LlmChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedLlmChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LlmChatService_ServiceDesc, srv)
}

func _LlmChatService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmChatServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmChatService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmChatServiceServer).Chat(ctx, req.(*ChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmChatService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatStreamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LlmChatServiceServer).ChatStream(m, &grpc.GenericServerStream[ChatStreamReq, ChatStreamResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LlmChatService_ChatStreamServer = grpc.ServerStreamingServer[ChatStreamResp]

// LlmChatService_ServiceDesc is the grpc.ServiceDesc for LlmChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LlmChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LlmChatService",
	HandlerType: (*LlmChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _LlmChatService_Chat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _LlmChatService_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "llmservice.proto",
}

const (
	LlmConfigService_CreateConfig_FullMethodName = "/pb.LlmConfigService/CreateConfig"
	LlmConfigService_DeleteConfig_FullMethodName = "/pb.LlmConfigService/DeleteConfig"
	LlmConfigService_UpdateConfig_FullMethodName = "/pb.LlmConfigService/UpdateConfig"
	LlmConfigService_GetConfig_FullMethodName    = "/pb.LlmConfigService/GetConfig"
	LlmConfigService_ListConfig_FullMethodName   = "/pb.LlmConfigService/ListConfig"
)

// LlmConfigServiceClient is the client API for LlmConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LlmConfigServiceClient interface {
	CreateConfig(ctx context.Context, in *CreateConfigReq, opts ...grpc.CallOption) (*CreateConfigResp, error)
	DeleteConfig(ctx context.Context, in *DeleteConfigReq, opts ...grpc.CallOption) (*DeleteConfigResp, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*UpdateConfigResp, error)
	GetConfig(ctx context.Context, in *GetConfigReq, opts ...grpc.CallOption) (*GetConfigResp, error)
	ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error)
}

type llmConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLlmConfigServiceClient(cc grpc.ClientConnInterface) LlmConfigServiceClient {
	return &llmConfigServiceClient{cc}
}

func (c *llmConfigServiceClient) CreateConfig(ctx context.Context, in *CreateConfigReq, opts ...grpc.CallOption) (*CreateConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConfigResp)
	err := c.cc.Invoke(ctx, LlmConfigService_CreateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmConfigServiceClient) DeleteConfig(ctx context.Context, in *DeleteConfigReq, opts ...grpc.CallOption) (*DeleteConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfigResp)
	err := c.cc.Invoke(ctx, LlmConfigService_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmConfigServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*UpdateConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResp)
	err := c.cc.Invoke(ctx, LlmConfigService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmConfigServiceClient) GetConfig(ctx context.Context, in *GetConfigReq, opts ...grpc.CallOption) (*GetConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResp)
	err := c.cc.Invoke(ctx, LlmConfigService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmConfigServiceClient) ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigResp)
	err := c.cc.Invoke(ctx, LlmConfigService_ListConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LlmConfigServiceServer is the server API for LlmConfigService service.
// All implementations must embed UnimplementedLlmConfigServiceServer
// for forward compatibility.
type LlmConfigServiceServer interface {
	CreateConfig(context.Context, *CreateConfigReq) (*CreateConfigResp, error)
	DeleteConfig(context.Context, *DeleteConfigReq) (*DeleteConfigResp, error)
	UpdateConfig(context.Context, *UpdateConfigReq) (*UpdateConfigResp, error)
	GetConfig(context.Context, *GetConfigReq) (*GetConfigResp, error)
	ListConfig(context.Context, *ListConfigReq) (*ListConfigResp, error)
	mustEmbedUnimplementedLlmConfigServiceServer()
}

// UnimplementedLlmConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlmConfigServiceServer struct{}

func (UnimplementedLlmConfigServiceServer) CreateConfig(context.Context, *CreateConfigReq) (*CreateConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConfig not implemented")
}
func (UnimplementedLlmConfigServiceServer) DeleteConfig(context.Context, *DeleteConfigReq) (*DeleteConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedLlmConfigServiceServer) UpdateConfig(context.Context, *UpdateConfigReq) (*UpdateConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedLlmConfigServiceServer) GetConfig(context.Context, *GetConfigReq) (*GetConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedLlmConfigServiceServer) ListConfig(context.Context, *ListConfigReq) (*ListConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfig not implemented")
}
func (UnimplementedLlmConfigServiceServer) mustEmbedUnimplementedLlmConfigServiceServer() {}
func (UnimplementedLlmConfigServiceServer) testEmbeddedByValue()                          {}

// UnsafeLlmConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlmConfigServiceServer will
// result in compilation errors.
type UnsafeLlmConfigServiceServer interface {
	mustEmbedUnimplementedLlmConfigServiceServer()
}

func RegisterLlmConfigServiceServer(s grpc.ServiceRegistrar, srv LlmConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedLlmConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LlmConfigService_ServiceDesc, srv)
}

func _LlmConfigService_CreateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmConfigServiceServer).CreateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmConfigService_CreateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmConfigServiceServer).CreateConfig(ctx, req.(*CreateConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmConfigService_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmConfigServiceServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmConfigService_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmConfigServiceServer).DeleteConfig(ctx, req.(*DeleteConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmConfigService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmConfigServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmConfigService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmConfigServiceServer).UpdateConfig(ctx, req.(*UpdateConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmConfigService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmConfigServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmConfigService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmConfigServiceServer).GetConfig(ctx, req.(*GetConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmConfigService_ListConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmConfigServiceServer).ListConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmConfigService_ListConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmConfigServiceServer).ListConfig(ctx, req.(*ListConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LlmConfigService_ServiceDesc is the grpc.ServiceDesc for LlmConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LlmConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LlmConfigService",
	HandlerType: (*LlmConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConfig",
			Handler:    _LlmConfigService_CreateConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _LlmConfigService_DeleteConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _LlmConfigService_UpdateConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _LlmConfigService_GetConfig_Handler,
		},
		{
			MethodName: "ListConfig",
			Handler:    _LlmConfigService_ListConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llmservice.proto",
}

const (
	ChatSessionService_CreateChatSession_FullMethodName      = "/pb.ChatSessionService/CreateChatSession"
	ChatSessionService_DeleteChatSession_FullMethodName      = "/pb.ChatSessionService/DeleteChatSession"
	ChatSessionService_UpdateChatSession_FullMethodName      = "/pb.ChatSessionService/UpdateChatSession"
	ChatSessionService_GetChatSession_FullMethodName         = "/pb.ChatSessionService/GetChatSession"
	ChatSessionService_GetChatSessionByConvId_FullMethodName = "/pb.ChatSessionService/GetChatSessionByConvId"
	ChatSessionService_ListChatSession_FullMethodName        = "/pb.ChatSessionService/ListChatSession"
)

// ChatSessionServiceClient is the client API for ChatSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatSessionServiceClient interface {
	CreateChatSession(ctx context.Context, in *CreateChatSessionReq, opts ...grpc.CallOption) (*CreateChatSessionResp, error)
	DeleteChatSession(ctx context.Context, in *DeleteChatSessionReq, opts ...grpc.CallOption) (*DeleteChatSessionResp, error)
	UpdateChatSession(ctx context.Context, in *UpdateChatSessionReq, opts ...grpc.CallOption) (*UpdateChatSessionResp, error)
	GetChatSession(ctx context.Context, in *GetChatSessionReq, opts ...grpc.CallOption) (*GetChatSessionResp, error)
	GetChatSessionByConvId(ctx context.Context, in *GetChatSessionByConvIdReq, opts ...grpc.CallOption) (*GetChatSessionResp, error)
	ListChatSession(ctx context.Context, in *ListChatSessionReq, opts ...grpc.CallOption) (*ListChatSessionResp, error)
}

type chatSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatSessionServiceClient(cc grpc.ClientConnInterface) ChatSessionServiceClient {
	return &chatSessionServiceClient{cc}
}

func (c *chatSessionServiceClient) CreateChatSession(ctx context.Context, in *CreateChatSessionReq, opts ...grpc.CallOption) (*CreateChatSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChatSessionResp)
	err := c.cc.Invoke(ctx, ChatSessionService_CreateChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatSessionServiceClient) DeleteChatSession(ctx context.Context, in *DeleteChatSessionReq, opts ...grpc.CallOption) (*DeleteChatSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChatSessionResp)
	err := c.cc.Invoke(ctx, ChatSessionService_DeleteChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatSessionServiceClient) UpdateChatSession(ctx context.Context, in *UpdateChatSessionReq, opts ...grpc.CallOption) (*UpdateChatSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateChatSessionResp)
	err := c.cc.Invoke(ctx, ChatSessionService_UpdateChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatSessionServiceClient) GetChatSession(ctx context.Context, in *GetChatSessionReq, opts ...grpc.CallOption) (*GetChatSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatSessionResp)
	err := c.cc.Invoke(ctx, ChatSessionService_GetChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatSessionServiceClient) GetChatSessionByConvId(ctx context.Context, in *GetChatSessionByConvIdReq, opts ...grpc.CallOption) (*GetChatSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatSessionResp)
	err := c.cc.Invoke(ctx, ChatSessionService_GetChatSessionByConvId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatSessionServiceClient) ListChatSession(ctx context.Context, in *ListChatSessionReq, opts ...grpc.CallOption) (*ListChatSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatSessionResp)
	err := c.cc.Invoke(ctx, ChatSessionService_ListChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatSessionServiceServer is the server API for ChatSessionService service.
// All implementations must embed UnimplementedChatSessionServiceServer
// for forward compatibility.
type ChatSessionServiceServer interface {
	CreateChatSession(context.Context, *CreateChatSessionReq) (*CreateChatSessionResp, error)
	DeleteChatSession(context.Context, *DeleteChatSessionReq) (*DeleteChatSessionResp, error)
	UpdateChatSession(context.Context, *UpdateChatSessionReq) (*UpdateChatSessionResp, error)
	GetChatSession(context.Context, *GetChatSessionReq) (*GetChatSessionResp, error)
	GetChatSessionByConvId(context.Context, *GetChatSessionByConvIdReq) (*GetChatSessionResp, error)
	ListChatSession(context.Context, *ListChatSessionReq) (*ListChatSessionResp, error)
	mustEmbedUnimplementedChatSessionServiceServer()
}

// UnimplementedChatSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatSessionServiceServer struct{}

func (UnimplementedChatSessionServiceServer) CreateChatSession(context.Context, *CreateChatSessionReq) (*CreateChatSessionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChatSession not implemented")
}
func (UnimplementedChatSessionServiceServer) DeleteChatSession(context.Context, *DeleteChatSessionReq) (*DeleteChatSessionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChatSession not implemented")
}
func (UnimplementedChatSessionServiceServer) UpdateChatSession(context.Context, *UpdateChatSessionReq) (*UpdateChatSessionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChatSession not implemented")
}
func (UnimplementedChatSessionServiceServer) GetChatSession(context.Context, *GetChatSessionReq) (*GetChatSessionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatSession not implemented")
}
func (UnimplementedChatSessionServiceServer) GetChatSessionByConvId(context.Context, *GetChatSessionByConvIdReq) (*GetChatSessionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatSessionByConvId not implemented")
}
func (UnimplementedChatSessionServiceServer) ListChatSession(context.Context, *ListChatSessionReq) (*ListChatSessionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChatSession not implemented")
}
func (UnimplementedChatSessionServiceServer) mustEmbedUnimplementedChatSessionServiceServer() {}
func (UnimplementedChatSessionServiceServer) testEmbeddedByValue()                            {}

// UnsafeChatSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatSessionServiceServer will
// result in compilation errors.
type UnsafeChatSessionServiceServer interface {
	mustEmbedUnimplementedChatSessionServiceServer()
}

func RegisterChatSessionServiceServer(s grpc.ServiceRegistrar, srv ChatSessionServiceServer) {
	// If the following call pancis, it indicates UnimplementedChatSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatSessionService_ServiceDesc, srv)
}

func _ChatSessionService_CreateChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).CreateChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_CreateChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).CreateChatSession(ctx, req.(*CreateChatSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatSessionService_DeleteChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).DeleteChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_DeleteChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).DeleteChatSession(ctx, req.(*DeleteChatSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatSessionService_UpdateChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChatSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).UpdateChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_UpdateChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).UpdateChatSession(ctx, req.(*UpdateChatSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatSessionService_GetChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).GetChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_GetChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).GetChatSession(ctx, req.(*GetChatSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatSessionService_GetChatSessionByConvId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatSessionByConvIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).GetChatSessionByConvId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_GetChatSessionByConvId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).GetChatSessionByConvId(ctx, req.(*GetChatSessionByConvIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatSessionService_ListChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatSessionServiceServer).ListChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatSessionService_ListChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatSessionServiceServer).ListChatSession(ctx, req.(*ListChatSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatSessionService_ServiceDesc is the grpc.ServiceDesc for ChatSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ChatSessionService",
	HandlerType: (*ChatSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChatSession",
			Handler:    _ChatSessionService_CreateChatSession_Handler,
		},
		{
			MethodName: "DeleteChatSession",
			Handler:    _ChatSessionService_DeleteChatSession_Handler,
		},
		{
			MethodName: "UpdateChatSession",
			Handler:    _ChatSessionService_UpdateChatSession_Handler,
		},
		{
			MethodName: "GetChatSession",
			Handler:    _ChatSessionService_GetChatSession_Handler,
		},
		{
			MethodName: "GetChatSessionByConvId",
			Handler:    _ChatSessionService_GetChatSessionByConvId_Handler,
		},
		{
			MethodName: "ListChatSession",
			Handler:    _ChatSessionService_ListChatSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llmservice.proto",
}
