// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"go-zero-voice-agent/pkg/globalkey"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chatConfigFieldNames          = builder.RawFieldNames(&ChatConfig{})
	chatConfigRows                = strings.Join(chatConfigFieldNames, ",")
	chatConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(chatConfigFieldNames, "`id`", "`create_time`", "`delete_time`", "`update_time`"), ",")
	chatConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(chatConfigFieldNames, "`id`", "`create_time`", "`delete_time`", "`update_time`"), "=?,") + "=?"

	cacheGzvaLlmserviceChatConfigIdPrefix = "cache:gzvaLlmservice:chatConfig:id:"
)

type (
	chatConfigModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ChatConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ChatConfig, error)
		Update(ctx context.Context, session sqlx.Session, data *ChatConfig) (sql.Result, error)

		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ChatConfig) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ChatConfig) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ChatConfig, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatConfig, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatConfig, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ChatConfig, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ChatConfig, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultChatConfigModel struct {
		sqlc.CachedConn
		table string
	}

	ChatConfig struct {
		Id                int64           `db:"id"`
		CreateTime        time.Time       `db:"create_time"`
		UpdateTime        time.Time       `db:"update_time"`
		DeleteTime        sql.NullTime    `db:"delete_time"`
		DelState          int64           `db:"del_state"`
		Version           int64           `db:"version"`
		Name              string          `db:"name"`
		Description       sql.NullString  `db:"description"`
		UserId            sql.NullInt64   `db:"user_id"`
		BaseUrl           sql.NullString  `db:"base_url"`
		ApiKey            sql.NullString  `db:"api_key"`
		Model             sql.NullString  `db:"model"`
		Stream            sql.NullInt64   `db:"stream"`
		Temperature       sql.NullFloat64 `db:"temperature"`
		TopP              sql.NullFloat64 `db:"top_p"`
		TopK              sql.NullInt64   `db:"top_k"`
		EnableThinking    sql.NullInt64   `db:"enable_thinking"`
		RepetitionPenalty sql.NullFloat64 `db:"repetition_penalty"`
		PresencePenalty   sql.NullFloat64 `db:"presence_penalty"`
		MaxTokens         sql.NullInt64   `db:"max_tokens"`
		Seed              sql.NullInt64   `db:"seed"`
		EnableSearch      sql.NullInt64   `db:"enable_search"`
		ContextLength     sql.NullInt64   `db:"context_length"`
	}
)

func newChatConfigModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultChatConfigModel {
	return &defaultChatConfigModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`chat_config`",
	}
}

func (m *defaultChatConfigModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	gzvaLlmserviceChatConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatConfigIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, gzvaLlmserviceChatConfigIdKey)
	return err
}
func (m *defaultChatConfigModel) FindOne(ctx context.Context, id int64) (*ChatConfig, error) {
	gzvaLlmserviceChatConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatConfigIdPrefix, id)
	var resp ChatConfig
	err := m.QueryRowCtx(ctx, &resp, gzvaLlmserviceChatConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatConfigModel) Insert(ctx context.Context, session sqlx.Session, data *ChatConfig) (sql.Result, error) {
	data.DelState = globalkey.DelStateNo
	gzvaLlmserviceChatConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatConfigIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, chatConfigRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DelState, data.Version, data.Name, data.Description, data.UserId, data.BaseUrl, data.ApiKey, data.Model, data.Stream, data.Temperature, data.TopP, data.TopK, data.EnableThinking, data.RepetitionPenalty, data.PresencePenalty, data.MaxTokens, data.Seed, data.EnableSearch, data.ContextLength)
		}
		return conn.ExecCtx(ctx, query, data.DelState, data.Version, data.Name, data.Description, data.UserId, data.BaseUrl, data.ApiKey, data.Model, data.Stream, data.Temperature, data.TopP, data.TopK, data.EnableThinking, data.RepetitionPenalty, data.PresencePenalty, data.MaxTokens, data.Seed, data.EnableSearch, data.ContextLength)
	}, gzvaLlmserviceChatConfigIdKey)
	return ret, err
}

func (m *defaultChatConfigModel) Update(ctx context.Context, session sqlx.Session, data *ChatConfig) (sql.Result, error) {
	gzvaLlmserviceChatConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatConfigIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatConfigRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DelState, data.Version, data.Name, data.Description, data.UserId, data.BaseUrl, data.ApiKey, data.Model, data.Stream, data.Temperature, data.TopP, data.TopK, data.EnableThinking, data.RepetitionPenalty, data.PresencePenalty, data.MaxTokens, data.Seed, data.EnableSearch, data.ContextLength, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.DelState, data.Version, data.Name, data.Description, data.UserId, data.BaseUrl, data.ApiKey, data.Model, data.Stream, data.Temperature, data.TopP, data.TopK, data.EnableThinking, data.RepetitionPenalty, data.PresencePenalty, data.MaxTokens, data.Seed, data.EnableSearch, data.ContextLength, data.Id)
	}, gzvaLlmserviceChatConfigIdKey)
}

func (m *defaultChatConfigModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ChatConfig) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	gzvaLlmserviceChatConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatConfigIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, chatConfigRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DelState, data.Version, data.Name, data.Description, data.UserId, data.BaseUrl, data.ApiKey, data.Model, data.Stream, data.Temperature, data.TopP, data.TopK, data.EnableThinking, data.RepetitionPenalty, data.PresencePenalty, data.MaxTokens, data.Seed, data.EnableSearch, data.ContextLength, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.DelState, data.Version, data.Name, data.Description, data.UserId, data.BaseUrl, data.ApiKey, data.Model, data.Stream, data.Temperature, data.TopP, data.TopK, data.EnableThinking, data.RepetitionPenalty, data.PresencePenalty, data.MaxTokens, data.Seed, data.EnableSearch, data.ContextLength, data.Id, oldVersion)
	}, gzvaLlmserviceChatConfigIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultChatConfigModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ChatConfig) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{
		Time:  time.Now(),
		Valid: true,
	}
	data.Version += 1

	var sqlResult sql.Result
	var err error

	gzvaLlmserviceChatConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatConfigIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set del_state = ?, delete_time = ?, version = ? where `id` = ? and version = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, globalkey.DelStateYes, data.DeleteTime, data.Version, data.Id, data.Version-1)
		}
		return conn.ExecCtx(ctx, query, globalkey.DelStateYes, data.DeleteTime, data.Version, data.Id, data.Version-1)
	}, gzvaLlmserviceChatConfigIdKey)
	if err != nil {
		return errors.Wrapf(errors.New("delete soft failed"), "ChatConfigModel delete err : %+v", err)
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}
	return nil
}
func (m *defaultChatConfigModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatConfigIdPrefix, primary)
}

func (m *defaultChatConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultChatConfigModel) tableName() string {
	return m.table
}

func (m *defaultChatConfigModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultChatConfigModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultChatConfigModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ChatConfig, error) {

	builder = builder.Columns(chatConfigRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatConfig
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatConfigModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatConfig, error) {

	builder = builder.Columns(chatConfigRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatConfig
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatConfigModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatConfig, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(chatConfigRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ChatConfig
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultChatConfigModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ChatConfig, error) {

	builder = builder.Columns(chatConfigRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatConfig
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatConfigModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ChatConfig, error) {

	builder = builder.Columns(chatConfigRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatConfig
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatConfigModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultChatConfigModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
