// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type UploadDocReq struct {
	UserId   int64  `header:"X-User-Id"`
	FileName string `form:"filename"`
}

type UploadDocResp struct {
	Path string `json:"path"`
}
