// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: rag.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=filePath,proto3" json:"filePath,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,6,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileReq) Reset() {
	*x = UploadFileReq{}
	mi := &file_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileReq) ProtoMessage() {}

func (x *UploadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileReq.ProtoReflect.Descriptor instead.
func (*UploadFileReq) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileReq) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UploadFileReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadFileReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadFileReq) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type UploadFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResp) Reset() {
	*x = UploadFileResp{}
	mi := &file_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResp) ProtoMessage() {}

func (x *UploadFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResp.ProtoReflect.Descriptor instead.
func (*UploadFileResp) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResp) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type QueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	FileId        string                 `protobuf:"bytes,3,opt,name=fileId,proto3" json:"fileId,omitempty"`
	TopK          int32                  `protobuf:"varint,4,opt,name=topK,proto3" json:"topK,omitempty"`
	EntityId      string                 `protobuf:"bytes,5,opt,name=entityId,proto3" json:"entityId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReq) Reset() {
	*x = QueryReq{}
	mi := &file_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReq) ProtoMessage() {}

func (x *QueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReq.ProtoReflect.Descriptor instead.
func (*QueryReq) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{2}
}

func (x *QueryReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *QueryReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *QueryReq) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type QueryMultipleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	FileIds       []string               `protobuf:"bytes,3,rep,name=fileIds,proto3" json:"fileIds,omitempty"`
	TopK          int32                  `protobuf:"varint,4,opt,name=topK,proto3" json:"topK,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMultipleReq) Reset() {
	*x = QueryMultipleReq{}
	mi := &file_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMultipleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMultipleReq) ProtoMessage() {}

func (x *QueryMultipleReq) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMultipleReq.ProtoReflect.Descriptor instead.
func (*QueryMultipleReq) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{3}
}

func (x *QueryMultipleReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryMultipleReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryMultipleReq) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

func (x *QueryMultipleReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type RetrievalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageContent   string                 `protobuf:"bytes,1,opt,name=pageContent,proto3" json:"pageContent,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalResult) Reset() {
	*x = RetrievalResult{}
	mi := &file_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalResult) ProtoMessage() {}

func (x *RetrievalResult) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalResult.ProtoReflect.Descriptor instead.
func (*RetrievalResult) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{4}
}

func (x *RetrievalResult) GetPageContent() string {
	if x != nil {
		return x.PageContent
	}
	return ""
}

func (x *RetrievalResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RetrievalResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type QueryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RetrievalResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResp) Reset() {
	*x = QueryResp{}
	mi := &file_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResp) ProtoMessage() {}

func (x *QueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResp.ProtoReflect.Descriptor instead.
func (*QueryResp) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResp) GetResults() []*RetrievalResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type FetchDocumentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDocumentsReq) Reset() {
	*x = FetchDocumentsReq{}
	mi := &file_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDocumentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDocumentsReq) ProtoMessage() {}

func (x *FetchDocumentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDocumentsReq.ProtoReflect.Descriptor instead.
func (*FetchDocumentsReq) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{6}
}

func (x *FetchDocumentsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FetchDocumentsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DocumentRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageContent   string                 `protobuf:"bytes,1,opt,name=pageContent,proto3" json:"pageContent,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRecord) Reset() {
	*x = DocumentRecord{}
	mi := &file_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRecord) ProtoMessage() {}

func (x *DocumentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRecord.ProtoReflect.Descriptor instead.
func (*DocumentRecord) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{7}
}

func (x *DocumentRecord) GetPageContent() string {
	if x != nil {
		return x.PageContent
	}
	return ""
}

func (x *DocumentRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FetchDocumentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*DocumentRecord      `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDocumentsResp) Reset() {
	*x = FetchDocumentsResp{}
	mi := &file_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDocumentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDocumentsResp) ProtoMessage() {}

func (x *FetchDocumentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDocumentsResp.ProtoReflect.Descriptor instead.
func (*FetchDocumentsResp) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{8}
}

func (x *FetchDocumentsResp) GetDocuments() []*DocumentRecord {
	if x != nil {
		return x.Documents
	}
	return nil
}

type DeleteDocumentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentsReq) Reset() {
	*x = DeleteDocumentsReq{}
	mi := &file_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentsReq) ProtoMessage() {}

func (x *DeleteDocumentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentsReq.ProtoReflect.Descriptor instead.
func (*DeleteDocumentsReq) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDocumentsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteDocumentsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteDocumentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deletedCount,proto3" json:"deletedCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentsResp) Reset() {
	*x = DeleteDocumentsResp{}
	mi := &file_rag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentsResp) ProtoMessage() {}

func (x *DeleteDocumentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentsResp.ProtoReflect.Descriptor instead.
func (*DeleteDocumentsResp) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDocumentsResp) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_rag_proto protoreflect.FileDescriptor

const file_rag_proto_rawDesc = "" +
	"\n" +
	"\trag.proto\x12\x02pb\"\xb4\x01\n" +
	"\rUploadFileReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x1a\n" +
	"\bfilePath\x18\x03 \x01(\tR\bfilePath\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bfileSize\x18\x05 \x01(\x03R\bfileSize\x12\x14\n" +
	"\x05chunk\x18\x06 \x01(\fR\x05chunk\"-\n" +
	"\x0eUploadFileResp\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"\x80\x01\n" +
	"\bQueryReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x16\n" +
	"\x06fileId\x18\x03 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04topK\x18\x04 \x01(\x05R\x04topK\x12\x1a\n" +
	"\bentityId\x18\x05 \x01(\tR\bentityId\"n\n" +
	"\x10QueryMultipleReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x18\n" +
	"\afileIds\x18\x03 \x03(\tR\afileIds\x12\x12\n" +
	"\x04topK\x18\x04 \x01(\x05R\x04topK\"\xc5\x01\n" +
	"\x0fRetrievalResult\x12 \n" +
	"\vpageContent\x18\x01 \x01(\tR\vpageContent\x12=\n" +
	"\bmetadata\x18\x02 \x03(\v2!.pb.RetrievalResult.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\tQueryResp\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.pb.RetrievalResultR\aresults\"=\n" +
	"\x11FetchDocumentsReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"\xad\x01\n" +
	"\x0eDocumentRecord\x12 \n" +
	"\vpageContent\x18\x01 \x01(\tR\vpageContent\x12<\n" +
	"\bmetadata\x18\x02 \x03(\v2 .pb.DocumentRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x12FetchDocumentsResp\x120\n" +
	"\tdocuments\x18\x01 \x03(\v2\x12.pb.DocumentRecordR\tdocuments\">\n" +
	"\x12DeleteDocumentsReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"9\n" +
	"\x13DeleteDocumentsResp\x12\"\n" +
	"\fdeletedCount\x18\x01 \x01(\x05R\fdeletedCount2\xc8\x01\n" +
	"\n" +
	"DocService\x125\n" +
	"\n" +
	"UploadFile\x12\x11.pb.UploadFileReq\x1a\x12.pb.UploadFileResp(\x01\x12?\n" +
	"\x0eFetchDocuments\x12\x15.pb.FetchDocumentsReq\x1a\x16.pb.FetchDocumentsResp\x12B\n" +
	"\x0fDeleteDocuments\x12\x16.pb.DeleteDocumentsReq\x1a\x17.pb.DeleteDocumentsResp2h\n" +
	"\n" +
	"RagService\x12$\n" +
	"\x05Query\x12\f.pb.QueryReq\x1a\r.pb.QueryResp\x124\n" +
	"\rQueryMultiple\x12\x14.pb.QueryMultipleReq\x1a\r.pb.QueryRespB\x06Z\x04./pbb\x06proto3"

var (
	file_rag_proto_rawDescOnce sync.Once
	file_rag_proto_rawDescData []byte
)

func file_rag_proto_rawDescGZIP() []byte {
	file_rag_proto_rawDescOnce.Do(func() {
		file_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)))
	})
	return file_rag_proto_rawDescData
}

var file_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rag_proto_goTypes = []any{
	(*UploadFileReq)(nil),       // 0: pb.UploadFileReq
	(*UploadFileResp)(nil),      // 1: pb.UploadFileResp
	(*QueryReq)(nil),            // 2: pb.QueryReq
	(*QueryMultipleReq)(nil),    // 3: pb.QueryMultipleReq
	(*RetrievalResult)(nil),     // 4: pb.RetrievalResult
	(*QueryResp)(nil),           // 5: pb.QueryResp
	(*FetchDocumentsReq)(nil),   // 6: pb.FetchDocumentsReq
	(*DocumentRecord)(nil),      // 7: pb.DocumentRecord
	(*FetchDocumentsResp)(nil),  // 8: pb.FetchDocumentsResp
	(*DeleteDocumentsReq)(nil),  // 9: pb.DeleteDocumentsReq
	(*DeleteDocumentsResp)(nil), // 10: pb.DeleteDocumentsResp
	nil,                         // 11: pb.RetrievalResult.MetadataEntry
	nil,                         // 12: pb.DocumentRecord.MetadataEntry
}
var file_rag_proto_depIdxs = []int32{
	11, // 0: pb.RetrievalResult.metadata:type_name -> pb.RetrievalResult.MetadataEntry
	4,  // 1: pb.QueryResp.results:type_name -> pb.RetrievalResult
	12, // 2: pb.DocumentRecord.metadata:type_name -> pb.DocumentRecord.MetadataEntry
	7,  // 3: pb.FetchDocumentsResp.documents:type_name -> pb.DocumentRecord
	0,  // 4: pb.DocService.UploadFile:input_type -> pb.UploadFileReq
	6,  // 5: pb.DocService.FetchDocuments:input_type -> pb.FetchDocumentsReq
	9,  // 6: pb.DocService.DeleteDocuments:input_type -> pb.DeleteDocumentsReq
	2,  // 7: pb.RagService.Query:input_type -> pb.QueryReq
	3,  // 8: pb.RagService.QueryMultiple:input_type -> pb.QueryMultipleReq
	1,  // 9: pb.DocService.UploadFile:output_type -> pb.UploadFileResp
	8,  // 10: pb.DocService.FetchDocuments:output_type -> pb.FetchDocumentsResp
	10, // 11: pb.DocService.DeleteDocuments:output_type -> pb.DeleteDocumentsResp
	5,  // 12: pb.RagService.Query:output_type -> pb.QueryResp
	5,  // 13: pb.RagService.QueryMultiple:output_type -> pb.QueryResp
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rag_proto_init() }
func file_rag_proto_init() {
	if File_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rag_proto_goTypes,
		DependencyIndexes: file_rag_proto_depIdxs,
		MessageInfos:      file_rag_proto_msgTypes,
	}.Build()
	File_rag_proto = out.File
	file_rag_proto_goTypes = nil
	file_rag_proto_depIdxs = nil
}
