// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rag.proto

package ragservice

import (
	"context"

	"go-zero-voice-agent/app/rag/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteDocumentsReq  = pb.DeleteDocumentsReq
	DeleteDocumentsResp = pb.DeleteDocumentsResp
	DocumentRecord      = pb.DocumentRecord
	FetchDocumentsReq   = pb.FetchDocumentsReq
	FetchDocumentsResp  = pb.FetchDocumentsResp
	QueryMultipleReq    = pb.QueryMultipleReq
	QueryReq            = pb.QueryReq
	QueryResp           = pb.QueryResp
	RetrievalResult     = pb.RetrievalResult
	UploadFileReq       = pb.UploadFileReq
	UploadFileResp      = pb.UploadFileResp

	RagService interface {
		Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error)
		QueryMultiple(ctx context.Context, in *QueryMultipleReq, opts ...grpc.CallOption) (*QueryResp, error)
	}

	defaultRagService struct {
		cli zrpc.Client
	}
)

func NewRagService(cli zrpc.Client) RagService {
	return &defaultRagService{
		cli: cli,
	}
}

func (m *defaultRagService) Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error) {
	client := pb.NewRagServiceClient(m.cli.Conn())
	return client.Query(ctx, in, opts...)
}

func (m *defaultRagService) QueryMultiple(ctx context.Context, in *QueryMultipleReq, opts ...grpc.CallOption) (*QueryResp, error) {
	client := pb.NewRagServiceClient(m.cli.Conn())
	return client.QueryMultiple(ctx, in, opts...)
}
