// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: voicechat.proto

package ttsconfigservice

import (
	"context"

	"go-zero-voice-agent/app/voicechat/cmd/rpc/voicechatpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AsrConfig               = voicechatpb.AsrConfig
	CreateAsrConfigRequest  = voicechatpb.CreateAsrConfigRequest
	CreateAsrConfigResponse = voicechatpb.CreateAsrConfigResponse
	CreateTtsConfigRequest  = voicechatpb.CreateTtsConfigRequest
	CreateTtsConfigResponse = voicechatpb.CreateTtsConfigResponse
	DeleteAsrConfigRequest  = voicechatpb.DeleteAsrConfigRequest
	DeleteAsrConfigResponse = voicechatpb.DeleteAsrConfigResponse
	DeleteTtsConfigRequest  = voicechatpb.DeleteTtsConfigRequest
	DeleteTtsConfigResponse = voicechatpb.DeleteTtsConfigResponse
	GetAsrConfigRequest     = voicechatpb.GetAsrConfigRequest
	GetAsrConfigResponse    = voicechatpb.GetAsrConfigResponse
	GetTtsConfigRequest     = voicechatpb.GetTtsConfigRequest
	GetTtsConfigResponse    = voicechatpb.GetTtsConfigResponse
	ListAsrConfigRequest    = voicechatpb.ListAsrConfigRequest
	ListAsrConfigResponse   = voicechatpb.ListAsrConfigResponse
	ListTtsConfigRequest    = voicechatpb.ListTtsConfigRequest
	ListTtsConfigResponse   = voicechatpb.ListTtsConfigResponse
	PageQuery               = voicechatpb.PageQuery
	TtsConfig               = voicechatpb.TtsConfig
	UpdateAsrConfigRequest  = voicechatpb.UpdateAsrConfigRequest
	UpdateAsrConfigResponse = voicechatpb.UpdateAsrConfigResponse
	UpdateTtsConfigRequest  = voicechatpb.UpdateTtsConfigRequest
	UpdateTtsConfigResponse = voicechatpb.UpdateTtsConfigResponse

	TtsConfigService interface {
		CreateTtsConfig(ctx context.Context, in *CreateTtsConfigRequest, opts ...grpc.CallOption) (*CreateTtsConfigResponse, error)
		GetTtsConfig(ctx context.Context, in *GetTtsConfigRequest, opts ...grpc.CallOption) (*GetTtsConfigResponse, error)
		UpdateTtsConfig(ctx context.Context, in *UpdateTtsConfigRequest, opts ...grpc.CallOption) (*UpdateTtsConfigResponse, error)
		DeleteTtsConfig(ctx context.Context, in *DeleteTtsConfigRequest, opts ...grpc.CallOption) (*DeleteTtsConfigResponse, error)
		ListTtsConfig(ctx context.Context, in *ListTtsConfigRequest, opts ...grpc.CallOption) (*ListTtsConfigResponse, error)
	}

	defaultTtsConfigService struct {
		cli zrpc.Client
	}
)

func NewTtsConfigService(cli zrpc.Client) TtsConfigService {
	return &defaultTtsConfigService{
		cli: cli,
	}
}

func (m *defaultTtsConfigService) CreateTtsConfig(ctx context.Context, in *CreateTtsConfigRequest, opts ...grpc.CallOption) (*CreateTtsConfigResponse, error) {
	client := voicechatpb.NewTtsConfigServiceClient(m.cli.Conn())
	return client.CreateTtsConfig(ctx, in, opts...)
}

func (m *defaultTtsConfigService) GetTtsConfig(ctx context.Context, in *GetTtsConfigRequest, opts ...grpc.CallOption) (*GetTtsConfigResponse, error) {
	client := voicechatpb.NewTtsConfigServiceClient(m.cli.Conn())
	return client.GetTtsConfig(ctx, in, opts...)
}

func (m *defaultTtsConfigService) UpdateTtsConfig(ctx context.Context, in *UpdateTtsConfigRequest, opts ...grpc.CallOption) (*UpdateTtsConfigResponse, error) {
	client := voicechatpb.NewTtsConfigServiceClient(m.cli.Conn())
	return client.UpdateTtsConfig(ctx, in, opts...)
}

func (m *defaultTtsConfigService) DeleteTtsConfig(ctx context.Context, in *DeleteTtsConfigRequest, opts ...grpc.CallOption) (*DeleteTtsConfigResponse, error) {
	client := voicechatpb.NewTtsConfigServiceClient(m.cli.Conn())
	return client.DeleteTtsConfig(ctx, in, opts...)
}

func (m *defaultTtsConfigService) ListTtsConfig(ctx context.Context, in *ListTtsConfigRequest, opts ...grpc.CallOption) (*ListTtsConfigResponse, error) {
	client := voicechatpb.NewTtsConfigServiceClient(m.cli.Conn())
	return client.ListTtsConfig(ctx, in, opts...)
}
