// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package llmservice

import (
	"context"

	"go-zero-voice-agent/app/llmservice/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatConfig       = pb.ChatConfig
	ChatMsg          = pb.ChatMsg
	ContinueChatReq  = pb.ContinueChatReq
	ContinueChatResp = pb.ContinueChatResp
	CreateChatReq    = pb.CreateChatReq
	CreateChatResp   = pb.CreateChatResp
	CreateConfigReq  = pb.CreateConfigReq
	CreateConfigResp = pb.CreateConfigResp
	DeleteConfigReq  = pb.DeleteConfigReq
	DeleteConfigResp = pb.DeleteConfigResp
	Function         = pb.Function
	GetConfigReq     = pb.GetConfigReq
	GetConfigResp    = pb.GetConfigResp
	ListConfigReq    = pb.ListConfigReq
	ListConfigResp   = pb.ListConfigResp
	LlmConfig        = pb.LlmConfig
	PageQuery        = pb.PageQuery
	StreamOptions    = pb.StreamOptions
	Tool             = pb.Tool
	UpdateConfigReq  = pb.UpdateConfigReq
	UpdateConfigResp = pb.UpdateConfigResp

	Llmservice interface {
		CreateChat(ctx context.Context, in *CreateChatReq, opts ...grpc.CallOption) (*CreateChatResp, error)
		ContinueChat(ctx context.Context, in *ContinueChatReq, opts ...grpc.CallOption) (*ContinueChatResp, error)
		CreateConfig(ctx context.Context, in *CreateConfigReq, opts ...grpc.CallOption) (*CreateConfigResp, error)
		DeleteConfig(ctx context.Context, in *DeleteConfigReq, opts ...grpc.CallOption) (*DeleteConfigResp, error)
		UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*UpdateConfigResp, error)
		GetConfig(ctx context.Context, in *GetConfigReq, opts ...grpc.CallOption) (*GetConfigResp, error)
		ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error)
	}

	defaultLlmservice struct {
		cli zrpc.Client
	}
)

func NewLlmservice(cli zrpc.Client) Llmservice {
	return &defaultLlmservice{
		cli: cli,
	}
}

func (m *defaultLlmservice) CreateChat(ctx context.Context, in *CreateChatReq, opts ...grpc.CallOption) (*CreateChatResp, error) {
	client := pb.NewLlmserviceClient(m.cli.Conn())
	return client.CreateChat(ctx, in, opts...)
}

func (m *defaultLlmservice) ContinueChat(ctx context.Context, in *ContinueChatReq, opts ...grpc.CallOption) (*ContinueChatResp, error) {
	client := pb.NewLlmserviceClient(m.cli.Conn())
	return client.ContinueChat(ctx, in, opts...)
}

func (m *defaultLlmservice) CreateConfig(ctx context.Context, in *CreateConfigReq, opts ...grpc.CallOption) (*CreateConfigResp, error) {
	client := pb.NewLlmserviceClient(m.cli.Conn())
	return client.CreateConfig(ctx, in, opts...)
}

func (m *defaultLlmservice) DeleteConfig(ctx context.Context, in *DeleteConfigReq, opts ...grpc.CallOption) (*DeleteConfigResp, error) {
	client := pb.NewLlmserviceClient(m.cli.Conn())
	return client.DeleteConfig(ctx, in, opts...)
}

func (m *defaultLlmservice) UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*UpdateConfigResp, error) {
	client := pb.NewLlmserviceClient(m.cli.Conn())
	return client.UpdateConfig(ctx, in, opts...)
}

func (m *defaultLlmservice) GetConfig(ctx context.Context, in *GetConfigReq, opts ...grpc.CallOption) (*GetConfigResp, error) {
	client := pb.NewLlmserviceClient(m.cli.Conn())
	return client.GetConfig(ctx, in, opts...)
}

func (m *defaultLlmservice) ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error) {
	client := pb.NewLlmserviceClient(m.cli.Conn())
	return client.ListConfig(ctx, in, opts...)
}
