// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package llmservice

import (
	"context"

	"go-zero-voice-agent/app/llmservice/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AudioOptions   = pb.AudioOptions
	ChatMsg        = pb.ChatMsg
	CreateChatReq  = pb.CreateChatReq
	CreateChatResp = pb.CreateChatResp
	Function       = pb.Function
	LlmConfig      = pb.LlmConfig
	StreamOptions  = pb.StreamOptions
	Tool           = pb.Tool

	Llmservice interface {
		CreateChat(ctx context.Context, in *CreateChatReq, opts ...grpc.CallOption) (*CreateChatResp, error)
	}

	defaultLlmservice struct {
		cli zrpc.Client
	}
)

func NewLlmservice(cli zrpc.Client) Llmservice {
	return &defaultLlmservice{
		cli: cli,
	}
}

func (m *defaultLlmservice) CreateChat(ctx context.Context, in *CreateChatReq, opts ...grpc.CallOption) (*CreateChatResp, error) {
	client := pb.NewLlmserviceClient(m.cli.Conn())
	return client.CreateChat(ctx, in, opts...)
}
