// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"go-zero-voice-agent/pkg/globalkey"
)

var (
	chatMessageFieldNames          = builder.RawFieldNames(&ChatMessage{})
	chatMessageRows                = strings.Join(chatMessageFieldNames, ",")
	chatMessageRowsExpectAutoSet   = strings.Join(stringx.Remove(chatMessageFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	chatMessageRowsWithPlaceHolder = strings.Join(stringx.Remove(chatMessageFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheGzvaLlmserviceChatMessageIdPrefix = "cache:gzvaLlmservice:chatMessage:id:"
)

type (
	chatMessageModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ChatMessage) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ChatMessage, error)
		Update(ctx context.Context, session sqlx.Session, data *ChatMessage) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ChatMessage) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ChatMessage) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ChatMessage, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatMessage, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatMessage, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ChatMessage, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ChatMessage, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultChatMessageModel struct {
		sqlc.CachedConn
		table string
	}

	ChatMessage struct {
		Id         int64          `db:"id"`
		CreateTime time.Time      `db:"create_time"`
		UpdateTime time.Time      `db:"update_time"`
		DeleteTime time.Time      `db:"delete_time"`
		DelState   int64          `db:"del_state"`
		Version    int64          `db:"version"`
		SessionId  int64          `db:"session_id"`
		ConfigId   sql.NullInt64  `db:"config_id"`
		Role       string         `db:"role"`
		Content    sql.NullString `db:"content"`
		Extra      sql.NullString `db:"extra"`
	}
)

func newChatMessageModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultChatMessageModel {
	return &defaultChatMessageModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`chat_message`",
	}
}

func (m *defaultChatMessageModel) Insert(ctx context.Context, session sqlx.Session, data *ChatMessage) (sql.Result, error) {
	data.DeleteTime = time.Now()
	data.DelState = globalkey.DelStateNo
	gzvaLlmserviceChatMessageIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatMessageIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, chatMessageRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.SessionId, data.ConfigId, data.Role, data.Content, data.Extra)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.SessionId, data.ConfigId, data.Role, data.Content, data.Extra)
	}, gzvaLlmserviceChatMessageIdKey)
}

func (m *defaultChatMessageModel) FindOne(ctx context.Context, id int64) (*ChatMessage, error) {
	gzvaLlmserviceChatMessageIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatMessageIdPrefix, id)
	var resp ChatMessage
	err := m.QueryRowCtx(ctx, &resp, gzvaLlmserviceChatMessageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", chatMessageRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatMessageModel) Update(ctx context.Context, session sqlx.Session, data *ChatMessage) (sql.Result, error) {
	gzvaLlmserviceChatMessageIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatMessageIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatMessageRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.SessionId, data.ConfigId, data.Role, data.Content, data.Extra, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.SessionId, data.ConfigId, data.Role, data.Content, data.Extra, data.Id)
	}, gzvaLlmserviceChatMessageIdKey)
}

func (m *defaultChatMessageModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ChatMessage) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	gzvaLlmserviceChatMessageIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatMessageIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, chatMessageRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.SessionId, data.ConfigId, data.Role, data.Content, data.Extra, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.SessionId, data.ConfigId, data.Role, data.Content, data.Extra, data.Id, oldVersion)
	}, gzvaLlmserviceChatMessageIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultChatMessageModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ChatMessage) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ChatMessageModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultChatMessageModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultChatMessageModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultChatMessageModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ChatMessage, error) {

	builder = builder.Columns(chatMessageRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatMessageModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatMessage, error) {

	builder = builder.Columns(chatMessageRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatMessageModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatMessage, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(chatMessageRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ChatMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultChatMessageModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ChatMessage, error) {

	builder = builder.Columns(chatMessageRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatMessageModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ChatMessage, error) {

	builder = builder.Columns(chatMessageRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatMessageModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultChatMessageModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultChatMessageModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	gzvaLlmserviceChatMessageIdKey := fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatMessageIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, gzvaLlmserviceChatMessageIdKey)
	return err
}
func (m *defaultChatMessageModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGzvaLlmserviceChatMessageIdPrefix, primary)
}
func (m *defaultChatMessageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", chatMessageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultChatMessageModel) tableName() string {
	return m.table
}
