// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package server

import (
	"context"

	"go-zero-voice-agent/app/llm/cmd/rpc/internal/logic/chatsessionservice"
	"go-zero-voice-agent/app/llm/cmd/rpc/internal/svc"
	"go-zero-voice-agent/app/llm/cmd/rpc/pb"
)

type ChatSessionServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedChatSessionServiceServer
}

func NewChatSessionServiceServer(svcCtx *svc.ServiceContext) *ChatSessionServiceServer {
	return &ChatSessionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatSessionServiceServer) CreateChatSession(ctx context.Context, in *pb.CreateChatSessionReq) (*pb.CreateChatSessionResp, error) {
	l := chatsessionservicelogic.NewCreateChatSessionLogic(ctx, s.svcCtx)
	return l.CreateChatSession(in)
}

func (s *ChatSessionServiceServer) DeleteChatSession(ctx context.Context, in *pb.DeleteChatSessionReq) (*pb.DeleteChatSessionResp, error) {
	l := chatsessionservicelogic.NewDeleteChatSessionLogic(ctx, s.svcCtx)
	return l.DeleteChatSession(in)
}

func (s *ChatSessionServiceServer) UpdateChatSession(ctx context.Context, in *pb.UpdateChatSessionReq) (*pb.UpdateChatSessionResp, error) {
	l := chatsessionservicelogic.NewUpdateChatSessionLogic(ctx, s.svcCtx)
	return l.UpdateChatSession(in)
}

func (s *ChatSessionServiceServer) GetChatSession(ctx context.Context, in *pb.GetChatSessionReq) (*pb.GetChatSessionResp, error) {
	l := chatsessionservicelogic.NewGetChatSessionLogic(ctx, s.svcCtx)
	return l.GetChatSession(in)
}

func (s *ChatSessionServiceServer) GetChatSessionByConvId(ctx context.Context, in *pb.GetChatSessionByConvIdReq) (*pb.GetChatSessionResp, error) {
	l := chatsessionservicelogic.NewGetChatSessionByConvIdLogic(ctx, s.svcCtx)
	return l.GetChatSessionByConvId(in)
}

func (s *ChatSessionServiceServer) ListChatSession(ctx context.Context, in *pb.ListChatSessionReq) (*pb.ListChatSessionResp, error) {
	l := chatsessionservicelogic.NewListChatSessionLogic(ctx, s.svcCtx)
	return l.ListChatSession(in)
}
