// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	ws "go-zero-voice-agent/app/chatroom/cmd/api/internal/handler/ws"
	"go-zero-voice-agent/app/chatroom/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建 WebSocket 连接
				Method:  http.MethodGet,
				Path:    "/open",
				Handler: ws.OpenConnectionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/ws/v1"),
	)
}
