// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package server

import (
	"context"

	"go-zero-voice-agent/app/llm/cmd/rpc/internal/logic/llmchatservice"
	"go-zero-voice-agent/app/llm/cmd/rpc/internal/svc"
	"go-zero-voice-agent/app/llm/cmd/rpc/pb"
)

type LlmChatServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLlmChatServiceServer
}

func NewLlmChatServiceServer(svcCtx *svc.ServiceContext) *LlmChatServiceServer {
	return &LlmChatServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LlmChatServiceServer) Chat(ctx context.Context, in *pb.ChatReq) (*pb.ChatResp, error) {
	l := llmchatservicelogic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}

func (s *LlmChatServiceServer) ChatStream(in *pb.ChatStreamReq, stream pb.LlmChatService_ChatStreamServer) error {
	l := llmchatservicelogic.NewChatStreamLogic(stream.Context(), s.svcCtx)
	return l.ChatStream(in, stream)
}

func (s *LlmChatServiceServer) ExecuteTool(ctx context.Context, in *pb.ExecuteToolReq) (*pb.ExecuteToolResp, error) {
	l := llmchatservicelogic.NewExecuteToolLogic(ctx, s.svcCtx)
	return l.ExecuteTool(in)
}
