// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: llmservice.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Llmservice_CreateChat_FullMethodName = "/pb.Llmservice/CreateChat"
)

// LlmserviceClient is the client API for Llmservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LlmserviceClient interface {
	CreateChat(ctx context.Context, in *CreateChatReq, opts ...grpc.CallOption) (*CreateChatResp, error)
}

type llmserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewLlmserviceClient(cc grpc.ClientConnInterface) LlmserviceClient {
	return &llmserviceClient{cc}
}

func (c *llmserviceClient) CreateChat(ctx context.Context, in *CreateChatReq, opts ...grpc.CallOption) (*CreateChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChatResp)
	err := c.cc.Invoke(ctx, Llmservice_CreateChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LlmserviceServer is the server API for Llmservice service.
// All implementations must embed UnimplementedLlmserviceServer
// for forward compatibility.
type LlmserviceServer interface {
	CreateChat(context.Context, *CreateChatReq) (*CreateChatResp, error)
	mustEmbedUnimplementedLlmserviceServer()
}

// UnimplementedLlmserviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlmserviceServer struct{}

func (UnimplementedLlmserviceServer) CreateChat(context.Context, *CreateChatReq) (*CreateChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChat not implemented")
}
func (UnimplementedLlmserviceServer) mustEmbedUnimplementedLlmserviceServer() {}
func (UnimplementedLlmserviceServer) testEmbeddedByValue()                    {}

// UnsafeLlmserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlmserviceServer will
// result in compilation errors.
type UnsafeLlmserviceServer interface {
	mustEmbedUnimplementedLlmserviceServer()
}

func RegisterLlmserviceServer(s grpc.ServiceRegistrar, srv LlmserviceServer) {
	// If the following call pancis, it indicates UnimplementedLlmserviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Llmservice_ServiceDesc, srv)
}

func _Llmservice_CreateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmserviceServer).CreateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Llmservice_CreateChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmserviceServer).CreateChat(ctx, req.(*CreateChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Llmservice_ServiceDesc is the grpc.ServiceDesc for Llmservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Llmservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Llmservice",
	HandlerType: (*LlmserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChat",
			Handler:    _Llmservice_CreateChat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llmservice.proto",
}
