package webrtc

const (
	WEBRTC_SIGNALING_OFFER  = "offer"
	WEBRTC_SIGNALING_ANSWER = "answer"

	WS_CALLBACK_EVENT_TYPE_INVITE   = "invite"
	WS_CALLBACK_EVENT_TYPE_TTS      = "tts"
	WS_CALLBACK_EVENT_TYPE_ANSWER   = "answer"
	WS_CALLBACK_EVENT_TYPE_ASRFINAL = "asrFinal"

	WS_CALLBACK_EVENT_TYPE_TRACK_START = "trackStart"
	WS_CALLBACK_EVENT_TYPE_TRACK_END   = "trackEnd"
	WS_CALLBACK_EVENT_TYPE_METRICS     = "metrics"
	WS_CALLBACK_EVENT_TYPE_ASRDELTA    = "asrDelta"

	LLM_USER_MESSAGE_ROLE      = "llmUser"
	LLM_ASSISTANT_MESSAGE_ROLE = "llmAssistant"
)
