// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package llmchatservice

import (
	"context"

	"go-zero-voice-agent/app/llm/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatConfig                = pb.ChatConfig
	ChatMessage               = pb.ChatMessage
	ChatMsg                   = pb.ChatMsg
	ChatReq                   = pb.ChatReq
	ChatResp                  = pb.ChatResp
	ChatSession               = pb.ChatSession
	ChatStreamReq             = pb.ChatStreamReq
	ChatStreamResp            = pb.ChatStreamResp
	CreateChatMessageReq      = pb.CreateChatMessageReq
	CreateChatMessageResp     = pb.CreateChatMessageResp
	CreateChatSessionReq      = pb.CreateChatSessionReq
	CreateChatSessionResp     = pb.CreateChatSessionResp
	CreateConfigReq           = pb.CreateConfigReq
	CreateConfigResp          = pb.CreateConfigResp
	DeleteChatMessageReq      = pb.DeleteChatMessageReq
	DeleteChatMessageResp     = pb.DeleteChatMessageResp
	DeleteChatSessionReq      = pb.DeleteChatSessionReq
	DeleteChatSessionResp     = pb.DeleteChatSessionResp
	DeleteConfigReq           = pb.DeleteConfigReq
	DeleteConfigResp          = pb.DeleteConfigResp
	GetChatMessageReq         = pb.GetChatMessageReq
	GetChatMessageResp        = pb.GetChatMessageResp
	GetChatSessionByConvIdReq = pb.GetChatSessionByConvIdReq
	GetChatSessionReq         = pb.GetChatSessionReq
	GetChatSessionResp        = pb.GetChatSessionResp
	GetConfigReq              = pb.GetConfigReq
	GetConfigResp             = pb.GetConfigResp
	ListChatMessageFilter     = pb.ListChatMessageFilter
	ListChatMessageReq        = pb.ListChatMessageReq
	ListChatMessageResp       = pb.ListChatMessageResp
	ListChatSessionFilter     = pb.ListChatSessionFilter
	ListChatSessionReq        = pb.ListChatSessionReq
	ListChatSessionResp       = pb.ListChatSessionResp
	ListConfigFilter          = pb.ListConfigFilter
	ListConfigReq             = pb.ListConfigReq
	ListConfigResp            = pb.ListConfigResp
	LlmConfig                 = pb.LlmConfig
	PageQuery                 = pb.PageQuery
	StreamOptions             = pb.StreamOptions
	ToolCall                  = pb.ToolCall
	ToolCallInfo              = pb.ToolCallInfo
	UpdateChatMessageReq      = pb.UpdateChatMessageReq
	UpdateChatMessageResp     = pb.UpdateChatMessageResp
	UpdateChatSessionReq      = pb.UpdateChatSessionReq
	UpdateChatSessionResp     = pb.UpdateChatSessionResp
	UpdateConfigReq           = pb.UpdateConfigReq
	UpdateConfigResp          = pb.UpdateConfigResp

	LlmChatService interface {
		Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error)
		ChatStream(ctx context.Context, in *ChatStreamReq, opts ...grpc.CallOption) (pb.LlmChatService_ChatStreamClient, error)
	}

	defaultLlmChatService struct {
		cli zrpc.Client
	}
)

func NewLlmChatService(cli zrpc.Client) LlmChatService {
	return &defaultLlmChatService{
		cli: cli,
	}
}

func (m *defaultLlmChatService) Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error) {
	client := pb.NewLlmChatServiceClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}

func (m *defaultLlmChatService) ChatStream(ctx context.Context, in *ChatStreamReq, opts ...grpc.CallOption) (pb.LlmChatService_ChatStreamClient, error) {
	client := pb.NewLlmChatServiceClient(m.cli.Conn())
	return client.ChatStream(ctx, in, opts...)
}
