// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package llmchatservice

import (
	"context"

	"go-zero-voice-agent/app/llm/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatConfig       = pb.ChatConfig
	ChatMsg          = pb.ChatMsg
	ChatStreamReq    = pb.ChatStreamReq
	ChatStreamResp   = pb.ChatStreamResp
	ContinueChatReq  = pb.ContinueChatReq
	ContinueChatResp = pb.ContinueChatResp
	CreateChatReq    = pb.CreateChatReq
	CreateChatResp   = pb.CreateChatResp
	CreateConfigReq  = pb.CreateConfigReq
	CreateConfigResp = pb.CreateConfigResp
	DeleteConfigReq  = pb.DeleteConfigReq
	DeleteConfigResp = pb.DeleteConfigResp
	Function         = pb.Function
	GetConfigReq     = pb.GetConfigReq
	GetConfigResp    = pb.GetConfigResp
	ListConfigReq    = pb.ListConfigReq
	ListConfigResp   = pb.ListConfigResp
	LlmConfig        = pb.LlmConfig
	PageQuery        = pb.PageQuery
	StreamDelta      = pb.StreamDelta
	StreamOptions    = pb.StreamOptions
	Tool             = pb.Tool
	ToolCallDelta    = pb.ToolCallDelta
	UpdateConfigReq  = pb.UpdateConfigReq
	UpdateConfigResp = pb.UpdateConfigResp
	UsageData        = pb.UsageData

	LlmChatService interface {
		CreateChat(ctx context.Context, in *CreateChatReq, opts ...grpc.CallOption) (*CreateChatResp, error)
		ContinueChat(ctx context.Context, in *ContinueChatReq, opts ...grpc.CallOption) (*ContinueChatResp, error)
		ChatStream(ctx context.Context, in *ChatStreamReq, opts ...grpc.CallOption) (pb.LlmChatService_ChatStreamClient, error)
	}

	defaultLlmChatService struct {
		cli zrpc.Client
	}
)

func NewLlmChatService(cli zrpc.Client) LlmChatService {
	return &defaultLlmChatService{
		cli: cli,
	}
}

func (m *defaultLlmChatService) CreateChat(ctx context.Context, in *CreateChatReq, opts ...grpc.CallOption) (*CreateChatResp, error) {
	client := pb.NewLlmChatServiceClient(m.cli.Conn())
	return client.CreateChat(ctx, in, opts...)
}

func (m *defaultLlmChatService) ContinueChat(ctx context.Context, in *ContinueChatReq, opts ...grpc.CallOption) (*ContinueChatResp, error) {
	client := pb.NewLlmChatServiceClient(m.cli.Conn())
	return client.ContinueChat(ctx, in, opts...)
}

func (m *defaultLlmChatService) ChatStream(ctx context.Context, in *ChatStreamReq, opts ...grpc.CallOption) (pb.LlmChatService_ChatStreamClient, error) {
	client := pb.NewLlmChatServiceClient(m.cli.Conn())
	return client.ChatStream(ctx, in, opts...)
}
