// ...existing code...

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: voicechat.proto

package voicechatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分页查询通用
type PageQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageQuery) Reset() {
	*x = PageQuery{}
	mi := &file_voicechat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageQuery) ProtoMessage() {}

func (x *PageQuery) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageQuery.ProtoReflect.Descriptor instead.
func (*PageQuery) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{0}
}

func (x *PageQuery) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageQuery) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageQuery) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// 数据结构
type AsrConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=Provider,proto3" json:"Provider,omitempty"`
	AppId         string                 `protobuf:"bytes,4,opt,name=AppId,proto3" json:"AppId,omitempty"`
	SecretId      string                 `protobuf:"bytes,5,opt,name=SecretId,proto3" json:"SecretId,omitempty"`
	SecretKey     string                 `protobuf:"bytes,6,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	Language      string                 `protobuf:"bytes,7,opt,name=Language,proto3" json:"Language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsrConfig) Reset() {
	*x = AsrConfig{}
	mi := &file_voicechat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsrConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsrConfig) ProtoMessage() {}

func (x *AsrConfig) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsrConfig.ProtoReflect.Descriptor instead.
func (*AsrConfig) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{1}
}

func (x *AsrConfig) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AsrConfig) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AsrConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AsrConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AsrConfig) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *AsrConfig) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *AsrConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type TtsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=Provider,proto3" json:"Provider,omitempty"`
	AppId         string                 `protobuf:"bytes,4,opt,name=AppId,proto3" json:"AppId,omitempty"`
	SecretId      string                 `protobuf:"bytes,5,opt,name=SecretId,proto3" json:"SecretId,omitempty"`
	SecretKey     string                 `protobuf:"bytes,6,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsConfig) Reset() {
	*x = TtsConfig{}
	mi := &file_voicechat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsConfig) ProtoMessage() {}

func (x *TtsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsConfig.ProtoReflect.Descriptor instead.
func (*TtsConfig) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{2}
}

func (x *TtsConfig) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TtsConfig) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TtsConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TtsConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *TtsConfig) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *TtsConfig) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

// AsrConfig CRUD & List
type CreateAsrConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=Provider,proto3" json:"Provider,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=AppId,proto3" json:"AppId,omitempty"`
	SecretId      string                 `protobuf:"bytes,4,opt,name=SecretId,proto3" json:"SecretId,omitempty"`
	SecretKey     string                 `protobuf:"bytes,5,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=Language,proto3" json:"Language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAsrConfigRequest) Reset() {
	*x = CreateAsrConfigRequest{}
	mi := &file_voicechat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAsrConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAsrConfigRequest) ProtoMessage() {}

func (x *CreateAsrConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAsrConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateAsrConfigRequest) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAsrConfigRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAsrConfigRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateAsrConfigRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateAsrConfigRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *CreateAsrConfigRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *CreateAsrConfigRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type CreateAsrConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AsrConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAsrConfigResponse) Reset() {
	*x = CreateAsrConfigResponse{}
	mi := &file_voicechat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAsrConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAsrConfigResponse) ProtoMessage() {}

func (x *CreateAsrConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAsrConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateAsrConfigResponse) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAsrConfigResponse) GetConfig() *AsrConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetAsrConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAsrConfigRequest) Reset() {
	*x = GetAsrConfigRequest{}
	mi := &file_voicechat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAsrConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAsrConfigRequest) ProtoMessage() {}

func (x *GetAsrConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAsrConfigRequest.ProtoReflect.Descriptor instead.
func (*GetAsrConfigRequest) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{5}
}

func (x *GetAsrConfigRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAsrConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AsrConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAsrConfigResponse) Reset() {
	*x = GetAsrConfigResponse{}
	mi := &file_voicechat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAsrConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAsrConfigResponse) ProtoMessage() {}

func (x *GetAsrConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAsrConfigResponse.ProtoReflect.Descriptor instead.
func (*GetAsrConfigResponse) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{6}
}

func (x *GetAsrConfigResponse) GetConfig() *AsrConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateAsrConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AsrConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAsrConfigRequest) Reset() {
	*x = UpdateAsrConfigRequest{}
	mi := &file_voicechat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAsrConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAsrConfigRequest) ProtoMessage() {}

func (x *UpdateAsrConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAsrConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateAsrConfigRequest) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAsrConfigRequest) GetConfig() *AsrConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateAsrConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AsrConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAsrConfigResponse) Reset() {
	*x = UpdateAsrConfigResponse{}
	mi := &file_voicechat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAsrConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAsrConfigResponse) ProtoMessage() {}

func (x *UpdateAsrConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAsrConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateAsrConfigResponse) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAsrConfigResponse) GetConfig() *AsrConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteAsrConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAsrConfigRequest) Reset() {
	*x = DeleteAsrConfigRequest{}
	mi := &file_voicechat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAsrConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAsrConfigRequest) ProtoMessage() {}

func (x *DeleteAsrConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAsrConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteAsrConfigRequest) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAsrConfigRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAsrConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAsrConfigResponse) Reset() {
	*x = DeleteAsrConfigResponse{}
	mi := &file_voicechat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAsrConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAsrConfigResponse) ProtoMessage() {}

func (x *DeleteAsrConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAsrConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteAsrConfigResponse) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAsrConfigResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListAsrConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageQuery             `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAsrConfigRequest) Reset() {
	*x = ListAsrConfigRequest{}
	mi := &file_voicechat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAsrConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAsrConfigRequest) ProtoMessage() {}

func (x *ListAsrConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAsrConfigRequest.ProtoReflect.Descriptor instead.
func (*ListAsrConfigRequest) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{11}
}

func (x *ListAsrConfigRequest) GetPage() *PageQuery {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListAsrConfigRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListAsrConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*AsrConfig           `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAsrConfigResponse) Reset() {
	*x = ListAsrConfigResponse{}
	mi := &file_voicechat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAsrConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAsrConfigResponse) ProtoMessage() {}

func (x *ListAsrConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAsrConfigResponse.ProtoReflect.Descriptor instead.
func (*ListAsrConfigResponse) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{12}
}

func (x *ListAsrConfigResponse) GetConfigs() []*AsrConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ListAsrConfigResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// TtsConfig CRUD & List
type CreateTtsConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=Provider,proto3" json:"Provider,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=AppId,proto3" json:"AppId,omitempty"`
	SecretId      string                 `protobuf:"bytes,4,opt,name=SecretId,proto3" json:"SecretId,omitempty"`
	SecretKey     string                 `protobuf:"bytes,5,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTtsConfigRequest) Reset() {
	*x = CreateTtsConfigRequest{}
	mi := &file_voicechat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTtsConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTtsConfigRequest) ProtoMessage() {}

func (x *CreateTtsConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTtsConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateTtsConfigRequest) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTtsConfigRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTtsConfigRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateTtsConfigRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateTtsConfigRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *CreateTtsConfigRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type CreateTtsConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *TtsConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTtsConfigResponse) Reset() {
	*x = CreateTtsConfigResponse{}
	mi := &file_voicechat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTtsConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTtsConfigResponse) ProtoMessage() {}

func (x *CreateTtsConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTtsConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateTtsConfigResponse) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{14}
}

func (x *CreateTtsConfigResponse) GetConfig() *TtsConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetTtsConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTtsConfigRequest) Reset() {
	*x = GetTtsConfigRequest{}
	mi := &file_voicechat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTtsConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTtsConfigRequest) ProtoMessage() {}

func (x *GetTtsConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTtsConfigRequest.ProtoReflect.Descriptor instead.
func (*GetTtsConfigRequest) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{15}
}

func (x *GetTtsConfigRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTtsConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *TtsConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTtsConfigResponse) Reset() {
	*x = GetTtsConfigResponse{}
	mi := &file_voicechat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTtsConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTtsConfigResponse) ProtoMessage() {}

func (x *GetTtsConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTtsConfigResponse.ProtoReflect.Descriptor instead.
func (*GetTtsConfigResponse) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{16}
}

func (x *GetTtsConfigResponse) GetConfig() *TtsConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateTtsConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *TtsConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTtsConfigRequest) Reset() {
	*x = UpdateTtsConfigRequest{}
	mi := &file_voicechat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTtsConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTtsConfigRequest) ProtoMessage() {}

func (x *UpdateTtsConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTtsConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateTtsConfigRequest) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateTtsConfigRequest) GetConfig() *TtsConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateTtsConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *TtsConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTtsConfigResponse) Reset() {
	*x = UpdateTtsConfigResponse{}
	mi := &file_voicechat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTtsConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTtsConfigResponse) ProtoMessage() {}

func (x *UpdateTtsConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTtsConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateTtsConfigResponse) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateTtsConfigResponse) GetConfig() *TtsConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteTtsConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTtsConfigRequest) Reset() {
	*x = DeleteTtsConfigRequest{}
	mi := &file_voicechat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTtsConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTtsConfigRequest) ProtoMessage() {}

func (x *DeleteTtsConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTtsConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteTtsConfigRequest) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteTtsConfigRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTtsConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTtsConfigResponse) Reset() {
	*x = DeleteTtsConfigResponse{}
	mi := &file_voicechat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTtsConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTtsConfigResponse) ProtoMessage() {}

func (x *DeleteTtsConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTtsConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteTtsConfigResponse) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteTtsConfigResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListTtsConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageQuery             `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTtsConfigRequest) Reset() {
	*x = ListTtsConfigRequest{}
	mi := &file_voicechat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTtsConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTtsConfigRequest) ProtoMessage() {}

func (x *ListTtsConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTtsConfigRequest.ProtoReflect.Descriptor instead.
func (*ListTtsConfigRequest) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{21}
}

func (x *ListTtsConfigRequest) GetPage() *PageQuery {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListTtsConfigRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTtsConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*TtsConfig           `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTtsConfigResponse) Reset() {
	*x = ListTtsConfigResponse{}
	mi := &file_voicechat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTtsConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTtsConfigResponse) ProtoMessage() {}

func (x *ListTtsConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicechat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTtsConfigResponse.ProtoReflect.Descriptor instead.
func (*ListTtsConfigResponse) Descriptor() ([]byte, []int) {
	return file_voicechat_proto_rawDescGZIP(), []int{22}
}

func (x *ListTtsConfigResponse) GetConfigs() []*TtsConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ListTtsConfigResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_voicechat_proto protoreflect.FileDescriptor

const file_voicechat_proto_rawDesc = "" +
	"\n" +
	"\x0fvoicechat.proto\x12\vvoicechatpb\"W\n" +
	"\tPageQuery\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\"\xbb\x01\n" +
	"\tAsrConfig\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bProvider\x18\x03 \x01(\tR\bProvider\x12\x14\n" +
	"\x05AppId\x18\x04 \x01(\tR\x05AppId\x12\x1a\n" +
	"\bSecretId\x18\x05 \x01(\tR\bSecretId\x12\x1c\n" +
	"\tSecretKey\x18\x06 \x01(\tR\tSecretKey\x12\x1a\n" +
	"\bLanguage\x18\a \x01(\tR\bLanguage\"\x9f\x01\n" +
	"\tTtsConfig\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bProvider\x18\x03 \x01(\tR\bProvider\x12\x14\n" +
	"\x05AppId\x18\x04 \x01(\tR\x05AppId\x12\x1a\n" +
	"\bSecretId\x18\x05 \x01(\tR\bSecretId\x12\x1c\n" +
	"\tSecretKey\x18\x06 \x01(\tR\tSecretKey\"\xb8\x01\n" +
	"\x16CreateAsrConfigRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bProvider\x18\x02 \x01(\tR\bProvider\x12\x14\n" +
	"\x05AppId\x18\x03 \x01(\tR\x05AppId\x12\x1a\n" +
	"\bSecretId\x18\x04 \x01(\tR\bSecretId\x12\x1c\n" +
	"\tSecretKey\x18\x05 \x01(\tR\tSecretKey\x12\x1a\n" +
	"\bLanguage\x18\x06 \x01(\tR\bLanguage\"I\n" +
	"\x17CreateAsrConfigResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.voicechatpb.AsrConfigR\x06config\"%\n" +
	"\x13GetAsrConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x14GetAsrConfigResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.voicechatpb.AsrConfigR\x06config\"H\n" +
	"\x16UpdateAsrConfigRequest\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.voicechatpb.AsrConfigR\x06config\"I\n" +
	"\x17UpdateAsrConfigResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.voicechatpb.AsrConfigR\x06config\"(\n" +
	"\x16DeleteAsrConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\x17DeleteAsrConfigResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"[\n" +
	"\x14ListAsrConfigRequest\x12*\n" +
	"\x04page\x18\x01 \x01(\v2\x16.voicechatpb.PageQueryR\x04page\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"_\n" +
	"\x15ListAsrConfigResponse\x120\n" +
	"\aconfigs\x18\x01 \x03(\v2\x16.voicechatpb.AsrConfigR\aconfigs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x9c\x01\n" +
	"\x16CreateTtsConfigRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bProvider\x18\x02 \x01(\tR\bProvider\x12\x14\n" +
	"\x05AppId\x18\x03 \x01(\tR\x05AppId\x12\x1a\n" +
	"\bSecretId\x18\x04 \x01(\tR\bSecretId\x12\x1c\n" +
	"\tSecretKey\x18\x05 \x01(\tR\tSecretKey\"I\n" +
	"\x17CreateTtsConfigResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.voicechatpb.TtsConfigR\x06config\"%\n" +
	"\x13GetTtsConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x14GetTtsConfigResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.voicechatpb.TtsConfigR\x06config\"H\n" +
	"\x16UpdateTtsConfigRequest\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.voicechatpb.TtsConfigR\x06config\"I\n" +
	"\x17UpdateTtsConfigResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.voicechatpb.TtsConfigR\x06config\"(\n" +
	"\x16DeleteTtsConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\x17DeleteTtsConfigResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"[\n" +
	"\x14ListTtsConfigRequest\x12*\n" +
	"\x04page\x18\x01 \x01(\v2\x16.voicechatpb.PageQueryR\x04page\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"_\n" +
	"\x15ListTtsConfigResponse\x120\n" +
	"\aconfigs\x18\x01 \x03(\v2\x16.voicechatpb.TtsConfigR\aconfigs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xd9\x03\n" +
	"\x10AsrConfigService\x12\\\n" +
	"\x0fCreateAsrConfig\x12#.voicechatpb.CreateAsrConfigRequest\x1a$.voicechatpb.CreateAsrConfigResponse\x12S\n" +
	"\fGetAsrConfig\x12 .voicechatpb.GetAsrConfigRequest\x1a!.voicechatpb.GetAsrConfigResponse\x12\\\n" +
	"\x0fUpdateAsrConfig\x12#.voicechatpb.UpdateAsrConfigRequest\x1a$.voicechatpb.UpdateAsrConfigResponse\x12\\\n" +
	"\x0fDeleteAsrConfig\x12#.voicechatpb.DeleteAsrConfigRequest\x1a$.voicechatpb.DeleteAsrConfigResponse\x12V\n" +
	"\rListAsrConfig\x12!.voicechatpb.ListAsrConfigRequest\x1a\".voicechatpb.ListAsrConfigResponse2\xd9\x03\n" +
	"\x10TtsConfigService\x12\\\n" +
	"\x0fCreateTtsConfig\x12#.voicechatpb.CreateTtsConfigRequest\x1a$.voicechatpb.CreateTtsConfigResponse\x12S\n" +
	"\fGetTtsConfig\x12 .voicechatpb.GetTtsConfigRequest\x1a!.voicechatpb.GetTtsConfigResponse\x12\\\n" +
	"\x0fUpdateTtsConfig\x12#.voicechatpb.UpdateTtsConfigRequest\x1a$.voicechatpb.UpdateTtsConfigResponse\x12\\\n" +
	"\x0fDeleteTtsConfig\x12#.voicechatpb.DeleteTtsConfigRequest\x1a$.voicechatpb.DeleteTtsConfigResponse\x12V\n" +
	"\rListTtsConfig\x12!.voicechatpb.ListTtsConfigRequest\x1a\".voicechatpb.ListTtsConfigResponseB\x0fZ\r./voicechatpbb\x06proto3"

var (
	file_voicechat_proto_rawDescOnce sync.Once
	file_voicechat_proto_rawDescData []byte
)

func file_voicechat_proto_rawDescGZIP() []byte {
	file_voicechat_proto_rawDescOnce.Do(func() {
		file_voicechat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voicechat_proto_rawDesc), len(file_voicechat_proto_rawDesc)))
	})
	return file_voicechat_proto_rawDescData
}

var file_voicechat_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_voicechat_proto_goTypes = []any{
	(*PageQuery)(nil),               // 0: voicechatpb.PageQuery
	(*AsrConfig)(nil),               // 1: voicechatpb.AsrConfig
	(*TtsConfig)(nil),               // 2: voicechatpb.TtsConfig
	(*CreateAsrConfigRequest)(nil),  // 3: voicechatpb.CreateAsrConfigRequest
	(*CreateAsrConfigResponse)(nil), // 4: voicechatpb.CreateAsrConfigResponse
	(*GetAsrConfigRequest)(nil),     // 5: voicechatpb.GetAsrConfigRequest
	(*GetAsrConfigResponse)(nil),    // 6: voicechatpb.GetAsrConfigResponse
	(*UpdateAsrConfigRequest)(nil),  // 7: voicechatpb.UpdateAsrConfigRequest
	(*UpdateAsrConfigResponse)(nil), // 8: voicechatpb.UpdateAsrConfigResponse
	(*DeleteAsrConfigRequest)(nil),  // 9: voicechatpb.DeleteAsrConfigRequest
	(*DeleteAsrConfigResponse)(nil), // 10: voicechatpb.DeleteAsrConfigResponse
	(*ListAsrConfigRequest)(nil),    // 11: voicechatpb.ListAsrConfigRequest
	(*ListAsrConfigResponse)(nil),   // 12: voicechatpb.ListAsrConfigResponse
	(*CreateTtsConfigRequest)(nil),  // 13: voicechatpb.CreateTtsConfigRequest
	(*CreateTtsConfigResponse)(nil), // 14: voicechatpb.CreateTtsConfigResponse
	(*GetTtsConfigRequest)(nil),     // 15: voicechatpb.GetTtsConfigRequest
	(*GetTtsConfigResponse)(nil),    // 16: voicechatpb.GetTtsConfigResponse
	(*UpdateTtsConfigRequest)(nil),  // 17: voicechatpb.UpdateTtsConfigRequest
	(*UpdateTtsConfigResponse)(nil), // 18: voicechatpb.UpdateTtsConfigResponse
	(*DeleteTtsConfigRequest)(nil),  // 19: voicechatpb.DeleteTtsConfigRequest
	(*DeleteTtsConfigResponse)(nil), // 20: voicechatpb.DeleteTtsConfigResponse
	(*ListTtsConfigRequest)(nil),    // 21: voicechatpb.ListTtsConfigRequest
	(*ListTtsConfigResponse)(nil),   // 22: voicechatpb.ListTtsConfigResponse
}
var file_voicechat_proto_depIdxs = []int32{
	1,  // 0: voicechatpb.CreateAsrConfigResponse.config:type_name -> voicechatpb.AsrConfig
	1,  // 1: voicechatpb.GetAsrConfigResponse.config:type_name -> voicechatpb.AsrConfig
	1,  // 2: voicechatpb.UpdateAsrConfigRequest.config:type_name -> voicechatpb.AsrConfig
	1,  // 3: voicechatpb.UpdateAsrConfigResponse.config:type_name -> voicechatpb.AsrConfig
	0,  // 4: voicechatpb.ListAsrConfigRequest.page:type_name -> voicechatpb.PageQuery
	1,  // 5: voicechatpb.ListAsrConfigResponse.configs:type_name -> voicechatpb.AsrConfig
	2,  // 6: voicechatpb.CreateTtsConfigResponse.config:type_name -> voicechatpb.TtsConfig
	2,  // 7: voicechatpb.GetTtsConfigResponse.config:type_name -> voicechatpb.TtsConfig
	2,  // 8: voicechatpb.UpdateTtsConfigRequest.config:type_name -> voicechatpb.TtsConfig
	2,  // 9: voicechatpb.UpdateTtsConfigResponse.config:type_name -> voicechatpb.TtsConfig
	0,  // 10: voicechatpb.ListTtsConfigRequest.page:type_name -> voicechatpb.PageQuery
	2,  // 11: voicechatpb.ListTtsConfigResponse.configs:type_name -> voicechatpb.TtsConfig
	3,  // 12: voicechatpb.AsrConfigService.CreateAsrConfig:input_type -> voicechatpb.CreateAsrConfigRequest
	5,  // 13: voicechatpb.AsrConfigService.GetAsrConfig:input_type -> voicechatpb.GetAsrConfigRequest
	7,  // 14: voicechatpb.AsrConfigService.UpdateAsrConfig:input_type -> voicechatpb.UpdateAsrConfigRequest
	9,  // 15: voicechatpb.AsrConfigService.DeleteAsrConfig:input_type -> voicechatpb.DeleteAsrConfigRequest
	11, // 16: voicechatpb.AsrConfigService.ListAsrConfig:input_type -> voicechatpb.ListAsrConfigRequest
	13, // 17: voicechatpb.TtsConfigService.CreateTtsConfig:input_type -> voicechatpb.CreateTtsConfigRequest
	15, // 18: voicechatpb.TtsConfigService.GetTtsConfig:input_type -> voicechatpb.GetTtsConfigRequest
	17, // 19: voicechatpb.TtsConfigService.UpdateTtsConfig:input_type -> voicechatpb.UpdateTtsConfigRequest
	19, // 20: voicechatpb.TtsConfigService.DeleteTtsConfig:input_type -> voicechatpb.DeleteTtsConfigRequest
	21, // 21: voicechatpb.TtsConfigService.ListTtsConfig:input_type -> voicechatpb.ListTtsConfigRequest
	4,  // 22: voicechatpb.AsrConfigService.CreateAsrConfig:output_type -> voicechatpb.CreateAsrConfigResponse
	6,  // 23: voicechatpb.AsrConfigService.GetAsrConfig:output_type -> voicechatpb.GetAsrConfigResponse
	8,  // 24: voicechatpb.AsrConfigService.UpdateAsrConfig:output_type -> voicechatpb.UpdateAsrConfigResponse
	10, // 25: voicechatpb.AsrConfigService.DeleteAsrConfig:output_type -> voicechatpb.DeleteAsrConfigResponse
	12, // 26: voicechatpb.AsrConfigService.ListAsrConfig:output_type -> voicechatpb.ListAsrConfigResponse
	14, // 27: voicechatpb.TtsConfigService.CreateTtsConfig:output_type -> voicechatpb.CreateTtsConfigResponse
	16, // 28: voicechatpb.TtsConfigService.GetTtsConfig:output_type -> voicechatpb.GetTtsConfigResponse
	18, // 29: voicechatpb.TtsConfigService.UpdateTtsConfig:output_type -> voicechatpb.UpdateTtsConfigResponse
	20, // 30: voicechatpb.TtsConfigService.DeleteTtsConfig:output_type -> voicechatpb.DeleteTtsConfigResponse
	22, // 31: voicechatpb.TtsConfigService.ListTtsConfig:output_type -> voicechatpb.ListTtsConfigResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_voicechat_proto_init() }
func file_voicechat_proto_init() {
	if File_voicechat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voicechat_proto_rawDesc), len(file_voicechat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_voicechat_proto_goTypes,
		DependencyIndexes: file_voicechat_proto_depIdxs,
		MessageInfos:      file_voicechat_proto_msgTypes,
	}.Build()
	File_voicechat_proto = out.File
	file_voicechat_proto_goTypes = nil
	file_voicechat_proto_depIdxs = nil
}
