// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package server

import (
	"context"

	"go-zero-voice-agent/app/llm/cmd/rpc/internal/logic/llmconfigservice"
	"go-zero-voice-agent/app/llm/cmd/rpc/internal/svc"
	"go-zero-voice-agent/app/llm/cmd/rpc/pb"
)

type LlmConfigServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLlmConfigServiceServer
}

func NewLlmConfigServiceServer(svcCtx *svc.ServiceContext) *LlmConfigServiceServer {
	return &LlmConfigServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LlmConfigServiceServer) CreateConfig(ctx context.Context, in *pb.CreateConfigReq) (*pb.CreateConfigResp, error) {
	l := llmconfigservicelogic.NewCreateConfigLogic(ctx, s.svcCtx)
	return l.CreateConfig(in)
}

func (s *LlmConfigServiceServer) DeleteConfig(ctx context.Context, in *pb.DeleteConfigReq) (*pb.DeleteConfigResp, error) {
	l := llmconfigservicelogic.NewDeleteConfigLogic(ctx, s.svcCtx)
	return l.DeleteConfig(in)
}

func (s *LlmConfigServiceServer) UpdateConfig(ctx context.Context, in *pb.UpdateConfigReq) (*pb.UpdateConfigResp, error) {
	l := llmconfigservicelogic.NewUpdateConfigLogic(ctx, s.svcCtx)
	return l.UpdateConfig(in)
}

func (s *LlmConfigServiceServer) GetConfig(ctx context.Context, in *pb.GetConfigReq) (*pb.GetConfigResp, error) {
	l := llmconfigservicelogic.NewGetConfigLogic(ctx, s.svcCtx)
	return l.GetConfig(in)
}

func (s *LlmConfigServiceServer) ListConfig(ctx context.Context, in *pb.ListConfigReq) (*pb.ListConfigResp, error) {
	l := llmconfigservicelogic.NewListConfigLogic(ctx, s.svcCtx)
	return l.ListConfig(in)
}
