// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package llmconfigservice

import (
	"context"

	"go-zero-voice-agent/app/llm/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatConfig                = pb.ChatConfig
	ChatMessage               = pb.ChatMessage
	ChatMsg                   = pb.ChatMsg
	ChatReq                   = pb.ChatReq
	ChatResp                  = pb.ChatResp
	ChatSession               = pb.ChatSession
	ChatStreamReq             = pb.ChatStreamReq
	ChatStreamResp            = pb.ChatStreamResp
	CreateChatMessageReq      = pb.CreateChatMessageReq
	CreateChatMessageResp     = pb.CreateChatMessageResp
	CreateChatSessionReq      = pb.CreateChatSessionReq
	CreateChatSessionResp     = pb.CreateChatSessionResp
	CreateConfigReq           = pb.CreateConfigReq
	CreateConfigResp          = pb.CreateConfigResp
	DeleteChatMessageReq      = pb.DeleteChatMessageReq
	DeleteChatMessageResp     = pb.DeleteChatMessageResp
	DeleteChatSessionReq      = pb.DeleteChatSessionReq
	DeleteChatSessionResp     = pb.DeleteChatSessionResp
	DeleteConfigReq           = pb.DeleteConfigReq
	DeleteConfigResp          = pb.DeleteConfigResp
	ExecuteToolReq            = pb.ExecuteToolReq
	ExecuteToolResp           = pb.ExecuteToolResp
	GetChatMessageReq         = pb.GetChatMessageReq
	GetChatMessageResp        = pb.GetChatMessageResp
	GetChatSessionByConvIdReq = pb.GetChatSessionByConvIdReq
	GetChatSessionReq         = pb.GetChatSessionReq
	GetChatSessionResp        = pb.GetChatSessionResp
	GetConfigReq              = pb.GetConfigReq
	GetConfigResp             = pb.GetConfigResp
	ListChatMessageFilter     = pb.ListChatMessageFilter
	ListChatMessageReq        = pb.ListChatMessageReq
	ListChatMessageResp       = pb.ListChatMessageResp
	ListChatSessionFilter     = pb.ListChatSessionFilter
	ListChatSessionReq        = pb.ListChatSessionReq
	ListChatSessionResp       = pb.ListChatSessionResp
	ListConfigFilter          = pb.ListConfigFilter
	ListConfigReq             = pb.ListConfigReq
	ListConfigResp            = pb.ListConfigResp
	LlmConfig                 = pb.LlmConfig
	PageQuery                 = pb.PageQuery
	StreamDelta               = pb.StreamDelta
	StreamOptions             = pb.StreamOptions
	ToolCallDelta             = pb.ToolCallDelta
	UpdateChatMessageReq      = pb.UpdateChatMessageReq
	UpdateChatMessageResp     = pb.UpdateChatMessageResp
	UpdateChatSessionReq      = pb.UpdateChatSessionReq
	UpdateChatSessionResp     = pb.UpdateChatSessionResp
	UpdateConfigReq           = pb.UpdateConfigReq
	UpdateConfigResp          = pb.UpdateConfigResp

	LlmConfigService interface {
		CreateConfig(ctx context.Context, in *CreateConfigReq, opts ...grpc.CallOption) (*CreateConfigResp, error)
		DeleteConfig(ctx context.Context, in *DeleteConfigReq, opts ...grpc.CallOption) (*DeleteConfigResp, error)
		UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*UpdateConfigResp, error)
		GetConfig(ctx context.Context, in *GetConfigReq, opts ...grpc.CallOption) (*GetConfigResp, error)
		ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error)
	}

	defaultLlmConfigService struct {
		cli zrpc.Client
	}
)

func NewLlmConfigService(cli zrpc.Client) LlmConfigService {
	return &defaultLlmConfigService{
		cli: cli,
	}
}

func (m *defaultLlmConfigService) CreateConfig(ctx context.Context, in *CreateConfigReq, opts ...grpc.CallOption) (*CreateConfigResp, error) {
	client := pb.NewLlmConfigServiceClient(m.cli.Conn())
	return client.CreateConfig(ctx, in, opts...)
}

func (m *defaultLlmConfigService) DeleteConfig(ctx context.Context, in *DeleteConfigReq, opts ...grpc.CallOption) (*DeleteConfigResp, error) {
	client := pb.NewLlmConfigServiceClient(m.cli.Conn())
	return client.DeleteConfig(ctx, in, opts...)
}

func (m *defaultLlmConfigService) UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*UpdateConfigResp, error) {
	client := pb.NewLlmConfigServiceClient(m.cli.Conn())
	return client.UpdateConfig(ctx, in, opts...)
}

func (m *defaultLlmConfigService) GetConfig(ctx context.Context, in *GetConfigReq, opts ...grpc.CallOption) (*GetConfigResp, error) {
	client := pb.NewLlmConfigServiceClient(m.cli.Conn())
	return client.GetConfig(ctx, in, opts...)
}

func (m *defaultLlmConfigService) ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error) {
	client := pb.NewLlmConfigServiceClient(m.cli.Conn())
	return client.ListConfig(ctx, in, opts...)
}
