// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package chatmessageservice

import (
	"context"

	"go-zero-voice-agent/app/llm/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatConfig                = pb.ChatConfig
	ChatMessage               = pb.ChatMessage
	ChatMsg                   = pb.ChatMsg
	ChatReq                   = pb.ChatReq
	ChatResp                  = pb.ChatResp
	ChatSession               = pb.ChatSession
	ChatStreamReq             = pb.ChatStreamReq
	ChatStreamResp            = pb.ChatStreamResp
	CreateChatMessageReq      = pb.CreateChatMessageReq
	CreateChatMessageResp     = pb.CreateChatMessageResp
	CreateChatSessionReq      = pb.CreateChatSessionReq
	CreateChatSessionResp     = pb.CreateChatSessionResp
	CreateConfigReq           = pb.CreateConfigReq
	CreateConfigResp          = pb.CreateConfigResp
	DeleteChatMessageReq      = pb.DeleteChatMessageReq
	DeleteChatMessageResp     = pb.DeleteChatMessageResp
	DeleteChatSessionReq      = pb.DeleteChatSessionReq
	DeleteChatSessionResp     = pb.DeleteChatSessionResp
	DeleteConfigReq           = pb.DeleteConfigReq
	DeleteConfigResp          = pb.DeleteConfigResp
	GetChatMessageReq         = pb.GetChatMessageReq
	GetChatMessageResp        = pb.GetChatMessageResp
	GetChatSessionByConvIdReq = pb.GetChatSessionByConvIdReq
	GetChatSessionReq         = pb.GetChatSessionReq
	GetChatSessionResp        = pb.GetChatSessionResp
	GetConfigReq              = pb.GetConfigReq
	GetConfigResp             = pb.GetConfigResp
	ListChatMessageFilter     = pb.ListChatMessageFilter
	ListChatMessageReq        = pb.ListChatMessageReq
	ListChatMessageResp       = pb.ListChatMessageResp
	ListChatSessionFilter     = pb.ListChatSessionFilter
	ListChatSessionReq        = pb.ListChatSessionReq
	ListChatSessionResp       = pb.ListChatSessionResp
	ListConfigFilter          = pb.ListConfigFilter
	ListConfigReq             = pb.ListConfigReq
	ListConfigResp            = pb.ListConfigResp
	LlmConfig                 = pb.LlmConfig
	PageQuery                 = pb.PageQuery
	StreamOptions             = pb.StreamOptions
	ToolCall                  = pb.ToolCall
	ToolCallInfo              = pb.ToolCallInfo
	UpdateChatMessageReq      = pb.UpdateChatMessageReq
	UpdateChatMessageResp     = pb.UpdateChatMessageResp
	UpdateChatSessionReq      = pb.UpdateChatSessionReq
	UpdateChatSessionResp     = pb.UpdateChatSessionResp
	UpdateConfigReq           = pb.UpdateConfigReq
	UpdateConfigResp          = pb.UpdateConfigResp

	ChatMessageService interface {
		CreateChatMessage(ctx context.Context, in *CreateChatMessageReq, opts ...grpc.CallOption) (*CreateChatMessageResp, error)
		DeleteChatMessage(ctx context.Context, in *DeleteChatMessageReq, opts ...grpc.CallOption) (*DeleteChatMessageResp, error)
		UpdateChatMessage(ctx context.Context, in *UpdateChatMessageReq, opts ...grpc.CallOption) (*UpdateChatMessageResp, error)
		GetChatMessage(ctx context.Context, in *GetChatMessageReq, opts ...grpc.CallOption) (*GetChatMessageResp, error)
		ListChatMessage(ctx context.Context, in *ListChatMessageReq, opts ...grpc.CallOption) (*ListChatMessageResp, error)
	}

	defaultChatMessageService struct {
		cli zrpc.Client
	}
)

func NewChatMessageService(cli zrpc.Client) ChatMessageService {
	return &defaultChatMessageService{
		cli: cli,
	}
}

func (m *defaultChatMessageService) CreateChatMessage(ctx context.Context, in *CreateChatMessageReq, opts ...grpc.CallOption) (*CreateChatMessageResp, error) {
	client := pb.NewChatMessageServiceClient(m.cli.Conn())
	return client.CreateChatMessage(ctx, in, opts...)
}

func (m *defaultChatMessageService) DeleteChatMessage(ctx context.Context, in *DeleteChatMessageReq, opts ...grpc.CallOption) (*DeleteChatMessageResp, error) {
	client := pb.NewChatMessageServiceClient(m.cli.Conn())
	return client.DeleteChatMessage(ctx, in, opts...)
}

func (m *defaultChatMessageService) UpdateChatMessage(ctx context.Context, in *UpdateChatMessageReq, opts ...grpc.CallOption) (*UpdateChatMessageResp, error) {
	client := pb.NewChatMessageServiceClient(m.cli.Conn())
	return client.UpdateChatMessage(ctx, in, opts...)
}

func (m *defaultChatMessageService) GetChatMessage(ctx context.Context, in *GetChatMessageReq, opts ...grpc.CallOption) (*GetChatMessageResp, error) {
	client := pb.NewChatMessageServiceClient(m.cli.Conn())
	return client.GetChatMessage(ctx, in, opts...)
}

func (m *defaultChatMessageService) ListChatMessage(ctx context.Context, in *ListChatMessageReq, opts ...grpc.CallOption) (*ListChatMessageResp, error) {
	client := pb.NewChatMessageServiceClient(m.cli.Conn())
	return client.ListChatMessage(ctx, in, opts...)
}
