// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rag.proto

package server

import (
	"context"

	"go-zero-voice-agent/app/rag/cmd/rpc/internal/logic/docservice"
	"go-zero-voice-agent/app/rag/cmd/rpc/internal/svc"
	"go-zero-voice-agent/app/rag/cmd/rpc/pb"
)

type DocServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDocServiceServer
}

func NewDocServiceServer(svcCtx *svc.ServiceContext) *DocServiceServer {
	return &DocServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DocServiceServer) UploadFile(stream pb.DocService_UploadFileServer) error {
	l := docservicelogic.NewUploadFileLogic(stream.Context(), s.svcCtx)
	return l.UploadFile(stream)
}

func (s *DocServiceServer) ListDocuments(ctx context.Context, in *pb.ListDocumentsReq) (*pb.ListDocumentsResp, error) {
	l := docservicelogic.NewListDocumentsLogic(ctx, s.svcCtx)
	return l.ListDocuments(in)
}

func (s *DocServiceServer) FetchDocuments(ctx context.Context, in *pb.FetchDocumentsReq) (*pb.FetchDocumentsResp, error) {
	l := docservicelogic.NewFetchDocumentsLogic(ctx, s.svcCtx)
	return l.FetchDocuments(in)
}

func (s *DocServiceServer) DeleteDocuments(ctx context.Context, in *pb.DeleteDocumentsReq) (*pb.DeleteDocumentsResp, error) {
	l := docservicelogic.NewDeleteDocumentsLogic(ctx, s.svcCtx)
	return l.DeleteDocuments(in)
}
