// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rag.proto

package server

import (
	"go-zero-voice-agent/app/rag/cmd/rpc/internal/logic/docservice"
	"go-zero-voice-agent/app/rag/cmd/rpc/internal/svc"
	"go-zero-voice-agent/app/rag/cmd/rpc/pb"
)

type DocServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDocServiceServer
}

func NewDocServiceServer(svcCtx *svc.ServiceContext) *DocServiceServer {
	return &DocServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DocServiceServer) UploadFile(stream pb.DocService_UploadFileServer) error {
	l := docservicelogic.NewUploadFileLogic(stream.Context(), s.svcCtx)
	return l.UploadFile(stream)
}
