// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"go-zero-voice-agent/pkg/globalkey"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	asrConfigFieldNames          = builder.RawFieldNames(&AsrConfig{})
	asrConfigRows                = strings.Join(asrConfigFieldNames, ",")
	asrConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(asrConfigFieldNames, "`id`", "`create_time`", "`delete_time`", "`update_time`"), ",")
	asrConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(asrConfigFieldNames, "`id`", "`create_time`", "`delete_time`", "`update_time`"), "=?,") + "=?"

	cacheGzvaVoicechatAsrConfigIdPrefix = "cache:gzvaVoicechat:asrConfig:id:"
)

type (
	asrConfigModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *AsrConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AsrConfig, error)
		Update(ctx context.Context, session sqlx.Session, data *AsrConfig) (sql.Result, error)

		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *AsrConfig) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *AsrConfig) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*AsrConfig, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*AsrConfig, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*AsrConfig, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*AsrConfig, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*AsrConfig, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultAsrConfigModel struct {
		sqlc.CachedConn
		table string
	}

	AsrConfig struct {
		Id         int64          `db:"id"`
		CreateTime time.Time      `db:"create_time"`
		UpdateTime time.Time      `db:"update_time"`
		DeleteTime sql.NullTime   `db:"delete_time"`
		DelState   int64          `db:"del_state"`
		Version    int64          `db:"version"`
		UserId     sql.NullInt64  `db:"user_id"`
		Provider   sql.NullString `db:"provider"`
		AppId      sql.NullString `db:"app_id"`
		SecretId   sql.NullString `db:"secret_id"`
		SecretKey  sql.NullString `db:"secret_key"`
		Language   sql.NullString `db:"language"`
	}
)

func newAsrConfigModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAsrConfigModel {
	return &defaultAsrConfigModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`asr_config`",
	}
}

func (m *defaultAsrConfigModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	gzvaVoicechatAsrConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaVoicechatAsrConfigIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, gzvaVoicechatAsrConfigIdKey)
	return err
}
func (m *defaultAsrConfigModel) FindOne(ctx context.Context, id int64) (*AsrConfig, error) {
	gzvaVoicechatAsrConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaVoicechatAsrConfigIdPrefix, id)
	var resp AsrConfig
	err := m.QueryRowCtx(ctx, &resp, gzvaVoicechatAsrConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", asrConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAsrConfigModel) Insert(ctx context.Context, session sqlx.Session, data *AsrConfig) (sql.Result, error) {
	data.DelState = globalkey.DelStateNo
	gzvaVoicechatAsrConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaVoicechatAsrConfigIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, asrConfigRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.Provider, data.AppId, data.SecretId, data.SecretKey, data.Language)
		}
		return conn.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.Provider, data.AppId, data.SecretId, data.SecretKey, data.Language)
	}, gzvaVoicechatAsrConfigIdKey)
	return ret, err
}

func (m *defaultAsrConfigModel) Update(ctx context.Context, session sqlx.Session, data *AsrConfig) (sql.Result, error) {
	gzvaVoicechatAsrConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaVoicechatAsrConfigIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, asrConfigRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.Provider, data.AppId, data.SecretId, data.SecretKey, data.Language, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.Provider, data.AppId, data.SecretId, data.SecretKey, data.Language, data.Id)
	}, gzvaVoicechatAsrConfigIdKey)
}

func (m *defaultAsrConfigModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *AsrConfig) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	gzvaVoicechatAsrConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaVoicechatAsrConfigIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, asrConfigRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.Provider, data.AppId, data.SecretId, data.SecretKey, data.Language, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.Provider, data.AppId, data.SecretId, data.SecretKey, data.Language, data.Id, oldVersion)
	}, gzvaVoicechatAsrConfigIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultAsrConfigModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *AsrConfig) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{
		Time:  time.Now(),
		Valid: true,
	}
	data.Version += 1

	var sqlResult sql.Result
	var err error

	gzvaVoicechatAsrConfigIdKey := fmt.Sprintf("%s%v", cacheGzvaVoicechatAsrConfigIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set del_state = ?, delete_time = ?, version = ? where `id` = ? and version = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, globalkey.DelStateYes, data.DeleteTime, data.Version, data.Id, data.Version-1)
		}
		return conn.ExecCtx(ctx, query, globalkey.DelStateYes, data.DeleteTime, data.Version, data.Id, data.Version-1)
	}, gzvaVoicechatAsrConfigIdKey)
	if err != nil {
		return errors.Wrapf(errors.New("delete soft failed"), "AsrConfigModel delete err : %+v", err)
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}
	return nil
}
func (m *defaultAsrConfigModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGzvaVoicechatAsrConfigIdPrefix, primary)
}

func (m *defaultAsrConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", asrConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAsrConfigModel) tableName() string {
	return m.table
}

func (m *defaultAsrConfigModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultAsrConfigModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultAsrConfigModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*AsrConfig, error) {

	builder = builder.Columns(asrConfigRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*AsrConfig
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultAsrConfigModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*AsrConfig, error) {

	builder = builder.Columns(asrConfigRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*AsrConfig
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultAsrConfigModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*AsrConfig, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(asrConfigRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*AsrConfig
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultAsrConfigModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*AsrConfig, error) {

	builder = builder.Columns(asrConfigRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*AsrConfig
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultAsrConfigModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*AsrConfig, error) {

	builder = builder.Columns(asrConfigRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*AsrConfig
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultAsrConfigModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultAsrConfigModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
