// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"go-zero-voice-agent/pkg/globalkey"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	fileUploadFieldNames          = builder.RawFieldNames(&FileUpload{})
	fileUploadRows                = strings.Join(fileUploadFieldNames, ",")
	fileUploadRowsExpectAutoSet   = strings.Join(stringx.Remove(fileUploadFieldNames, "`id`", "`create_time`", "`delete_time`", "`update_time`"), ",")
	fileUploadRowsWithPlaceHolder = strings.Join(stringx.Remove(fileUploadFieldNames, "`id`", "`create_time`", "`delete_time`", "`update_time`"), "=?,") + "=?"

	cacheGzvaRagFileUploadIdPrefix = "cache:gzvaRag:fileUpload:id:"
)

type (
	fileUploadModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *FileUpload) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*FileUpload, error)
		Update(ctx context.Context, session sqlx.Session, data *FileUpload) (sql.Result, error)

		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *FileUpload) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *FileUpload) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*FileUpload, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*FileUpload, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*FileUpload, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*FileUpload, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*FileUpload, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultFileUploadModel struct {
		sqlc.CachedConn
		table string
	}

	FileUpload struct {
		Id         int64          `db:"id"`
		CreateTime time.Time      `db:"create_time"`
		UpdateTime time.Time      `db:"update_time"`
		DeleteTime sql.NullTime   `db:"delete_time"`
		DelState   int64          `db:"del_state"`
		Version    int64          `db:"version"`
		UserId     sql.NullInt64  `db:"user_id"`
		FileName   string         `db:"file_name"`
		FileFormat sql.NullString `db:"file_format"` // 文件的格式
		BucketName sql.NullString `db:"bucket_name"`
		FilePath   string         `db:"file_path"`  // 文件存储路径
		StoreType  string         `db:"store_type"` // 存储方式：local,cors,minio
		Status     int64          `db:"status"`     // 是否向量化：否0，是1
	}
)

func newFileUploadModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFileUploadModel {
	return &defaultFileUploadModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`file_upload`",
	}
}

func (m *defaultFileUploadModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	gzvaRagFileUploadIdKey := fmt.Sprintf("%s%v", cacheGzvaRagFileUploadIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, gzvaRagFileUploadIdKey)
	return err
}
func (m *defaultFileUploadModel) FindOne(ctx context.Context, id int64) (*FileUpload, error) {
	gzvaRagFileUploadIdKey := fmt.Sprintf("%s%v", cacheGzvaRagFileUploadIdPrefix, id)
	var resp FileUpload
	err := m.QueryRowCtx(ctx, &resp, gzvaRagFileUploadIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", fileUploadRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileUploadModel) Insert(ctx context.Context, session sqlx.Session, data *FileUpload) (sql.Result, error) {
	data.DelState = globalkey.DelStateNo
	gzvaRagFileUploadIdKey := fmt.Sprintf("%s%v", cacheGzvaRagFileUploadIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, fileUploadRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.FileName, data.FileFormat, data.BucketName, data.FilePath, data.StoreType, data.Status)
		}
		return conn.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.FileName, data.FileFormat, data.BucketName, data.FilePath, data.StoreType, data.Status)
	}, gzvaRagFileUploadIdKey)
	return ret, err
}

func (m *defaultFileUploadModel) Update(ctx context.Context, session sqlx.Session, data *FileUpload) (sql.Result, error) {
	gzvaRagFileUploadIdKey := fmt.Sprintf("%s%v", cacheGzvaRagFileUploadIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, fileUploadRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.FileName, data.FileFormat, data.BucketName, data.FilePath, data.StoreType, data.Status, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.FileName, data.FileFormat, data.BucketName, data.FilePath, data.StoreType, data.Status, data.Id)
	}, gzvaRagFileUploadIdKey)
}

func (m *defaultFileUploadModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *FileUpload) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	gzvaRagFileUploadIdKey := fmt.Sprintf("%s%v", cacheGzvaRagFileUploadIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, fileUploadRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.FileName, data.FileFormat, data.BucketName, data.FilePath, data.StoreType, data.Status, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.DelState, data.Version, data.UserId, data.FileName, data.FileFormat, data.BucketName, data.FilePath, data.StoreType, data.Status, data.Id, oldVersion)
	}, gzvaRagFileUploadIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultFileUploadModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *FileUpload) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{
		Time:  time.Now(),
		Valid: true,
	}
	data.Version += 1

	var sqlResult sql.Result
	var err error

	gzvaRagFileUploadIdKey := fmt.Sprintf("%s%v", cacheGzvaRagFileUploadIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set del_state = ?, delete_time = ?, version = ? where `id` = ? and version = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, globalkey.DelStateYes, data.DeleteTime, data.Version, data.Id, data.Version-1)
		}
		return conn.ExecCtx(ctx, query, globalkey.DelStateYes, data.DeleteTime, data.Version, data.Id, data.Version-1)
	}, gzvaRagFileUploadIdKey)
	if err != nil {
		return errors.Wrapf(errors.New("delete soft failed"), "FileUploadModel delete err : %+v", err)
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}
	return nil
}
func (m *defaultFileUploadModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGzvaRagFileUploadIdPrefix, primary)
}

func (m *defaultFileUploadModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", fileUploadRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFileUploadModel) tableName() string {
	return m.table
}

func (m *defaultFileUploadModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultFileUploadModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultFileUploadModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*FileUpload, error) {

	builder = builder.Columns(fileUploadRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*FileUpload
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFileUploadModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*FileUpload, error) {

	builder = builder.Columns(fileUploadRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*FileUpload
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFileUploadModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*FileUpload, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(fileUploadRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*FileUpload
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultFileUploadModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*FileUpload, error) {

	builder = builder.Columns(fileUploadRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*FileUpload
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFileUploadModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*FileUpload, error) {

	builder = builder.Columns(fileUploadRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*FileUpload
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFileUploadModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultFileUploadModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
