// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: voicechat.proto

package server

import (
	"context"

	"go-zero-voice-agent/app/voicechat/cmd/rpc/internal/logic/ttsconfigservice"
	"go-zero-voice-agent/app/voicechat/cmd/rpc/internal/svc"
	"go-zero-voice-agent/app/voicechat/cmd/rpc/pb"
)

type TtsConfigServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTtsConfigServiceServer
}

func NewTtsConfigServiceServer(svcCtx *svc.ServiceContext) *TtsConfigServiceServer {
	return &TtsConfigServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TtsConfigServiceServer) CreateTtsConfig(ctx context.Context, in *pb.CreateTtsConfigRequest) (*pb.CreateTtsConfigResponse, error) {
	l := ttsconfigservicelogic.NewCreateTtsConfigLogic(ctx, s.svcCtx)
	return l.CreateTtsConfig(in)
}

func (s *TtsConfigServiceServer) GetTtsConfig(ctx context.Context, in *pb.GetTtsConfigRequest) (*pb.GetTtsConfigResponse, error) {
	l := ttsconfigservicelogic.NewGetTtsConfigLogic(ctx, s.svcCtx)
	return l.GetTtsConfig(in)
}

func (s *TtsConfigServiceServer) UpdateTtsConfig(ctx context.Context, in *pb.UpdateTtsConfigRequest) (*pb.UpdateTtsConfigResponse, error) {
	l := ttsconfigservicelogic.NewUpdateTtsConfigLogic(ctx, s.svcCtx)
	return l.UpdateTtsConfig(in)
}

func (s *TtsConfigServiceServer) DeleteTtsConfig(ctx context.Context, in *pb.DeleteTtsConfigRequest) (*pb.DeleteTtsConfigResponse, error) {
	l := ttsconfigservicelogic.NewDeleteTtsConfigLogic(ctx, s.svcCtx)
	return l.DeleteTtsConfig(in)
}

func (s *TtsConfigServiceServer) ListTtsConfig(ctx context.Context, in *pb.ListTtsConfigRequest) (*pb.ListTtsConfigResponse, error) {
	l := ttsconfigservicelogic.NewListTtsConfigLogic(ctx, s.svcCtx)
	return l.ListTtsConfig(in)
}
