// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: llmservice.proto

package chatsessionservice

import (
	"context"

	"go-zero-voice-agent/app/llm/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatConfig                = pb.ChatConfig
	ChatMessage               = pb.ChatMessage
	ChatMsg                   = pb.ChatMsg
	ChatReq                   = pb.ChatReq
	ChatResp                  = pb.ChatResp
	ChatSession               = pb.ChatSession
	ChatStreamReq             = pb.ChatStreamReq
	ChatStreamResp            = pb.ChatStreamResp
	CreateChatMessageReq      = pb.CreateChatMessageReq
	CreateChatMessageResp     = pb.CreateChatMessageResp
	CreateChatSessionReq      = pb.CreateChatSessionReq
	CreateChatSessionResp     = pb.CreateChatSessionResp
	CreateConfigReq           = pb.CreateConfigReq
	CreateConfigResp          = pb.CreateConfigResp
	DeleteChatMessageReq      = pb.DeleteChatMessageReq
	DeleteChatMessageResp     = pb.DeleteChatMessageResp
	DeleteChatSessionReq      = pb.DeleteChatSessionReq
	DeleteChatSessionResp     = pb.DeleteChatSessionResp
	DeleteConfigReq           = pb.DeleteConfigReq
	DeleteConfigResp          = pb.DeleteConfigResp
	GetChatMessageReq         = pb.GetChatMessageReq
	GetChatMessageResp        = pb.GetChatMessageResp
	GetChatSessionByConvIdReq = pb.GetChatSessionByConvIdReq
	GetChatSessionReq         = pb.GetChatSessionReq
	GetChatSessionResp        = pb.GetChatSessionResp
	GetConfigReq              = pb.GetConfigReq
	GetConfigResp             = pb.GetConfigResp
	ListChatMessageFilter     = pb.ListChatMessageFilter
	ListChatMessageReq        = pb.ListChatMessageReq
	ListChatMessageResp       = pb.ListChatMessageResp
	ListChatSessionFilter     = pb.ListChatSessionFilter
	ListChatSessionReq        = pb.ListChatSessionReq
	ListChatSessionResp       = pb.ListChatSessionResp
	ListConfigFilter          = pb.ListConfigFilter
	ListConfigReq             = pb.ListConfigReq
	ListConfigResp            = pb.ListConfigResp
	LlmConfig                 = pb.LlmConfig
	PageQuery                 = pb.PageQuery
	StreamDelta               = pb.StreamDelta
	StreamOptions             = pb.StreamOptions
	ToolCall                  = pb.ToolCall
	ToolCallInfo              = pb.ToolCallInfo
	UpdateChatMessageReq      = pb.UpdateChatMessageReq
	UpdateChatMessageResp     = pb.UpdateChatMessageResp
	UpdateChatSessionReq      = pb.UpdateChatSessionReq
	UpdateChatSessionResp     = pb.UpdateChatSessionResp
	UpdateConfigReq           = pb.UpdateConfigReq
	UpdateConfigResp          = pb.UpdateConfigResp

	ChatSessionService interface {
		CreateChatSession(ctx context.Context, in *CreateChatSessionReq, opts ...grpc.CallOption) (*CreateChatSessionResp, error)
		DeleteChatSession(ctx context.Context, in *DeleteChatSessionReq, opts ...grpc.CallOption) (*DeleteChatSessionResp, error)
		UpdateChatSession(ctx context.Context, in *UpdateChatSessionReq, opts ...grpc.CallOption) (*UpdateChatSessionResp, error)
		GetChatSession(ctx context.Context, in *GetChatSessionReq, opts ...grpc.CallOption) (*GetChatSessionResp, error)
		GetChatSessionByConvId(ctx context.Context, in *GetChatSessionByConvIdReq, opts ...grpc.CallOption) (*GetChatSessionResp, error)
		ListChatSession(ctx context.Context, in *ListChatSessionReq, opts ...grpc.CallOption) (*ListChatSessionResp, error)
	}

	defaultChatSessionService struct {
		cli zrpc.Client
	}
)

func NewChatSessionService(cli zrpc.Client) ChatSessionService {
	return &defaultChatSessionService{
		cli: cli,
	}
}

func (m *defaultChatSessionService) CreateChatSession(ctx context.Context, in *CreateChatSessionReq, opts ...grpc.CallOption) (*CreateChatSessionResp, error) {
	client := pb.NewChatSessionServiceClient(m.cli.Conn())
	return client.CreateChatSession(ctx, in, opts...)
}

func (m *defaultChatSessionService) DeleteChatSession(ctx context.Context, in *DeleteChatSessionReq, opts ...grpc.CallOption) (*DeleteChatSessionResp, error) {
	client := pb.NewChatSessionServiceClient(m.cli.Conn())
	return client.DeleteChatSession(ctx, in, opts...)
}

func (m *defaultChatSessionService) UpdateChatSession(ctx context.Context, in *UpdateChatSessionReq, opts ...grpc.CallOption) (*UpdateChatSessionResp, error) {
	client := pb.NewChatSessionServiceClient(m.cli.Conn())
	return client.UpdateChatSession(ctx, in, opts...)
}

func (m *defaultChatSessionService) GetChatSession(ctx context.Context, in *GetChatSessionReq, opts ...grpc.CallOption) (*GetChatSessionResp, error) {
	client := pb.NewChatSessionServiceClient(m.cli.Conn())
	return client.GetChatSession(ctx, in, opts...)
}

func (m *defaultChatSessionService) GetChatSessionByConvId(ctx context.Context, in *GetChatSessionByConvIdReq, opts ...grpc.CallOption) (*GetChatSessionResp, error) {
	client := pb.NewChatSessionServiceClient(m.cli.Conn())
	return client.GetChatSessionByConvId(ctx, in, opts...)
}

func (m *defaultChatSessionService) ListChatSession(ctx context.Context, in *ListChatSessionReq, opts ...grpc.CallOption) (*ListChatSessionResp, error) {
	client := pb.NewChatSessionServiceClient(m.cli.Conn())
	return client.ListChatSession(ctx, in, opts...)
}
